//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AllInformation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllInformation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.AllInformation", typeof(AllInformation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勘定科目.
        /// </summary>
        public static string ACCOUNT_CODE_MAINT {
            get {
                return ResourceManager.GetString("ACCOUNT_CODE_MAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力された全体掲載情報は既に存在しています。.
        /// </summary>
        public static string AllInformationDuplicateCode {
            get {
                return ResourceManager.GetString("AllInformationDuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全体掲載情報一覧.
        /// </summary>
        public static string AllInformationList {
            get {
                return ResourceManager.GetString("AllInformationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全体掲載情報登録.
        /// </summary>
        public static string AllInformationRegister {
            get {
                return ResourceManager.GetString("AllInformationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載終了日は掲載開始日以降を指定してください。.
        /// </summary>
        public static string AllInformationStartDateMustBeEarlierThanEndDate {
            get {
                return ResourceManager.GetString("AllInformationStartDateMustBeEarlierThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全体掲載情報を登録しました。.
        /// </summary>
        public static string AllInsertSuccess {
            get {
                return ResourceManager.GetString("AllInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全体掲載情報登録.
        /// </summary>
        public static string ALLREGISTER_INFO {
            get {
                return ResourceManager.GetString("ALLREGISTER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全体掲載情報を更新しました。.
        /// </summary>
        public static string AllUpdateSuccess {
            get {
                return ResourceManager.GetString("AllUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件クリア.
        /// </summary>
        public static string btnClearConditions {
            get {
                return ResourceManager.GetString("btnClearConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        public static string btnCreateNew {
            get {
                return ResourceManager.GetString("btnCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小カテゴリ.
        /// </summary>
        public static string CATEGORY_MAINT {
            get {
                return ResourceManager.GetString("CATEGORY_MAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業コード.
        /// </summary>
        public static string COMPANY_CD {
            get {
                return ResourceManager.GetString("COMPANY_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先担当者.
        /// </summary>
        public static string CONTACT_PERS_MAINT {
            get {
                return ResourceManager.GetString("CONTACT_PERS_MAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載内容.
        /// </summary>
        public static string CONTENT {
            get {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約プラン確認.
        /// </summary>
        public static string CONTRACT_PLAN_CONFIRMATION {
            get {
                return ResourceManager.GetString("CONTRACT_PLAN_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先.
        /// </summary>
        public static string CUST_MAINT {
            get {
                return ResourceManager.GetString("CUST_MAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日時.
        /// </summary>
        public static string DATE_MODIFY {
            get {
                return ResourceManager.GetString("DATE_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除フラグ.
        /// </summary>
        public static string DEL_FLG {
            get {
                return ResourceManager.GetString("DEL_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示優先度.
        /// </summary>
        public static string DSP_PRIORITY {
            get {
                return ResourceManager.GetString("DSP_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to は掲載開始日以降を指定してください。.
        /// </summary>
        public static string ERR_END_DATE {
            get {
                return ResourceManager.GetString("ERR_END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー情報.
        /// </summary>
        public static string ErrorInformation {
            get {
                return ResourceManager.GetString("ErrorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlsx.
        /// </summary>
        public static string ExcelExtension {
            get {
                return ResourceManager.GetString("ExcelExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載ID.
        /// </summary>
        public static string INFO_SEQ_NO {
            get {
                return ResourceManager.GetString("INFO_SEQ_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成日.
        /// </summary>
        public static string INS_DATE {
            get {
                return ResourceManager.GetString("INS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成者ID.
        /// </summary>
        public static string INS_USER_ID {
            get {
                return ResourceManager.GetString("INS_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全体掲載情報一覧.
        /// </summary>
        public static string lblAllInformationList {
            get {
                return ResourceManager.GetString("lblAllInformationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載区分.
        /// </summary>
        public static string lblContentType {
            get {
                return ResourceManager.GetString("lblContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間.
        /// </summary>
        public static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除済みを含む.
        /// </summary>
        public static string lblIncludeDeleted {
            get {
                return ResourceManager.GetString("lblIncludeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載情報一覧.
        /// </summary>
        public static string lblPostInformationList {
            get {
                return ResourceManager.GetString("lblPostInformationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 優先度.
        /// </summary>
        public static string lblPriority {
            get {
                return ResourceManager.GetString("lblPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトル.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日時.
        /// </summary>
        public static string lblUpdateTime {
            get {
                return ResourceManager.GetString("lblUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新者.
        /// </summary>
        public static string lblUpdateUser {
            get {
                return ResourceManager.GetString("lblUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ確認.
        /// </summary>
        public static string LOG_CONFIRM {
            get {
                return ResourceManager.GetString("LOG_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名情報.
        /// </summary>
        public static string NOMEN_MAINT {
            get {
                return ResourceManager.GetString("NOMEN_MAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組織.
        /// </summary>
        public static string ORG_MAINT {
            get {
                return ResourceManager.GetString("ORG_MAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者.
        /// </summary>
        public static string PERS_IN_CHAR_MAINT {
            get {
                return ResourceManager.GetString("PERS_IN_CHAR_MAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新者.
        /// </summary>
        public static string PERSON_UPDATE {
            get {
                return ResourceManager.GetString("PERSON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載終了日.
        /// </summary>
        public static string PUBLISH_DATE_END {
            get {
                return ResourceManager.GetString("PUBLISH_DATE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載開始日.
        /// </summary>
        public static string PUBLISH_DATE_START {
            get {
                return ResourceManager.GetString("PUBLISH_DATE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録日時.
        /// </summary>
        public static string REGISTER_DATE {
            get {
                return ResourceManager.GetString("REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載情報登録.
        /// </summary>
        public static string REGISTER_INFO {
            get {
                return ResourceManager.GetString("REGISTER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録者.
        /// </summary>
        public static string REGISTER_PERSON {
            get {
                return ResourceManager.GetString("REGISTER_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載情報を登録しました。.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補助科目.
        /// </summary>
        public static string SUBJECT_MAINT {
            get {
                return ResourceManager.GetString("SUBJECT_MAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自社銀行口座登録.
        /// </summary>
        public static string TRANS_MAINT {
            get {
                return ResourceManager.GetString("TRANS_MAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載情報.
        /// </summary>
        public static string txtPostInformationMaintenance {
            get {
                return ResourceManager.GetString("txtPostInformationMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日.
        /// </summary>
        public static string UPD_DATE {
            get {
                return ResourceManager.GetString("UPD_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新プログラムID.
        /// </summary>
        public static string UPD_PROG_ID {
            get {
                return ResourceManager.GetString("UPD_PROG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新者ID.
        /// </summary>
        public static string UPD_USER_ID {
            get {
                return ResourceManager.GetString("UPD_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載情報を更新しました。.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー.
        /// </summary>
        public static string USER_MAINT {
            get {
                return ResourceManager.GetString("USER_MAINT", resourceCulture);
            }
        }
    }
}
