//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillingInputDate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillingInputDate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.BillingInputDate", typeof(BillingInputDate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearchBilling {
            get {
                return ResourceManager.GetString("btnSearchBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearchDestination {
            get {
                return ResourceManager.GetString("btnSearchDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動更新.
        /// </summary>
        public static string lblAutoUpdate {
            get {
                return ResourceManager.GetString("lblAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string lblBillingDestination {
            get {
                return ResourceManager.GetString("lblBillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先カナ.
        /// </summary>
        public static string lblBillingDestinationKana {
            get {
                return ResourceManager.GetString("lblBillingDestinationKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求番号.
        /// </summary>
        public static string lblBillingNumber {
            get {
                return ResourceManager.GetString("lblBillingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求月.
        /// </summary>
        public static string lblBillingYear {
            get {
                return ResourceManager.GetString("lblBillingYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 締日.
        /// </summary>
        public static string lblClosingDay {
            get {
                return ResourceManager.GetString("lblClosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成状況.
        /// </summary>
        public static string lblCreateStatus {
            get {
                return ResourceManager.GetString("lblCreateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※必須入力.
        /// </summary>
        public static string lblInputRequired {
            get {
                return ResourceManager.GetString("lblInputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月分.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string lblProjectName {
            get {
                return ResourceManager.GetString("lblProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業者／品名.
        /// </summary>
        public static string lblWorkerProductName {
            get {
                return ResourceManager.GetString("lblWorkerProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て.
        /// </summary>
        public static string raAutoUpdateAll {
            get {
                return ResourceManager.GetString("raAutoUpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT自動更新.
        /// </summary>
        public static string raNotAutoUpdate {
            get {
                return ResourceManager.GetString("raNotAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動更新のみ.
        /// </summary>
        public static string raOnlyAutoUpdate {
            get {
                return ResourceManager.GetString("raOnlyAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て.
        /// </summary>
        public static string raStatusAll {
            get {
                return ResourceManager.GetString("raStatusAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成済み.
        /// </summary>
        public static string raStatusCreated {
            get {
                return ResourceManager.GetString("raStatusCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未作成.
        /// </summary>
        public static string raStatusNotCreated {
            get {
                return ResourceManager.GetString("raStatusNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約金額.
        /// </summary>
        public static string TH_BaseBillingAmount {
            get {
                return ResourceManager.GetString("TH_BaseBillingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求共有メモ.
        /// </summary>
        public static string TH_BillingCommonMemory {
            get {
                return ResourceManager.GetString("TH_BillingCommonMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string TH_BillingDestination {
            get {
                return ResourceManager.GetString("TH_BillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書作成日.
        /// </summary>
        public static string TH_BillingFileCreatedDate {
            get {
                return ResourceManager.GetString("TH_BillingFileCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求番号.
        /// </summary>
        public static string TH_BillingNumber {
            get {
                return ResourceManager.GetString("TH_BillingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求ルール.
        /// </summary>
        public static string TH_BillingRule {
            get {
                return ResourceManager.GetString("TH_BillingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間.
        /// </summary>
        public static string TH_ContractDuration {
            get {
                return ResourceManager.GetString("TH_ContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原本送付日.
        /// </summary>
        public static string TH_OriginalSendDate {
            get {
                return ResourceManager.GetString("TH_OriginalSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社内共有情報.
        /// </summary>
        public static string TH_PrivateNote {
            get {
                return ResourceManager.GetString("TH_PrivateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string TH_ProjectName {
            get {
                return ResourceManager.GetString("TH_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ送信日.
        /// </summary>
        public static string TH_SendDataDate {
            get {
                return ResourceManager.GetString("TH_SendDataDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業者／品名.
        /// </summary>
        public static string TH_WorkerProductName {
            get {
                return ResourceManager.GetString("TH_WorkerProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書日付入力.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
