//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillingSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillingSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.BillingSetting", typeof(BillingSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearchBilling {
            get {
                return ResourceManager.GetString("btnSearchBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearchDestination {
            get {
                return ResourceManager.GetString("btnSearchDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動更新.
        /// </summary>
        public static string lblAutoUpdate {
            get {
                return ResourceManager.GetString("lblAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string lblBillingDestination {
            get {
                return ResourceManager.GetString("lblBillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先カナ.
        /// </summary>
        public static string lblBillingDestinationKana {
            get {
                return ResourceManager.GetString("lblBillingDestinationKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求月.
        /// </summary>
        public static string lblBillingYear {
            get {
                return ResourceManager.GetString("lblBillingYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 締日.
        /// </summary>
        public static string lblClosingDay {
            get {
                return ResourceManager.GetString("lblClosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成状況.
        /// </summary>
        public static string lblCreateStatus {
            get {
                return ResourceManager.GetString("lblCreateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※必須入力.
        /// </summary>
        public static string lblInputRequired {
            get {
                return ResourceManager.GetString("lblInputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月分.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string lblProjectName {
            get {
                return ResourceManager.GetString("lblProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て.
        /// </summary>
        public static string raAutoUpdateAll {
            get {
                return ResourceManager.GetString("raAutoUpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT自動更新.
        /// </summary>
        public static string raNotAutoUpdate {
            get {
                return ResourceManager.GetString("raNotAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動更新のみ.
        /// </summary>
        public static string raOnlyAutoUpdate {
            get {
                return ResourceManager.GetString("raOnlyAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て.
        /// </summary>
        public static string raStatusAll {
            get {
                return ResourceManager.GetString("raStatusAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成済み.
        /// </summary>
        public static string raStatusCreated {
            get {
                return ResourceManager.GetString("raStatusCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未作成.
        /// </summary>
        public static string raStatusNotCreated {
            get {
                return ResourceManager.GetString("raStatusNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引落先口座情報.
        /// </summary>
        public static string TH_BankAccountInformation {
            get {
                return ResourceManager.GetString("TH_BankAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書送付先.
        /// </summary>
        public static string TH_BillingAddress {
            get {
                return ResourceManager.GetString("TH_BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税抜請求額.
        /// </summary>
        public static string TH_BillingAmountTaxExcluded {
            get {
                return ResourceManager.GetString("TH_BillingAmountTaxExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string TH_BillingDestination {
            get {
                return ResourceManager.GetString("TH_BillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書発行日付.
        /// </summary>
        public static string TH_BillingIssueDate {
            get {
                return ResourceManager.GetString("TH_BillingIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自社担当.
        /// </summary>
        public static string TH_CustomerPIC {
            get {
                return ResourceManager.GetString("TH_CustomerPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払サイト.
        /// </summary>
        public static string TH_PaymentSite {
            get {
                return ResourceManager.GetString("TH_PaymentSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件詳細名.
        /// </summary>
        public static string TH_ProjectDetailName {
            get {
                return ResourceManager.GetString("TH_ProjectDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string TH_ProjectName {
            get {
                return ResourceManager.GetString("TH_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回収方法.
        /// </summary>
        public static string TH_RecoveryProcess {
            get {
                return ResourceManager.GetString("TH_RecoveryProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振込先.
        /// </summary>
        public static string TH_TransferDestination {
            get {
                return ResourceManager.GetString("TH_TransferDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書各種設定.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
