//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillingInputPrivate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillingInputPrivate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.BillingInputPrivate", typeof(BillingInputPrivate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精算方法.
        /// </summary>
        public static string lblAdjustedMethod {
            get {
                return ResourceManager.GetString("lblAdjustedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精算月.
        /// </summary>
        public static string lblAdjustedMonth {
            get {
                return ResourceManager.GetString("lblAdjustedMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額.
        /// </summary>
        public static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額（粗利益）.
        /// </summary>
        public static string lblAmountGrossProfit {
            get {
                return ResourceManager.GetString("lblAmountGrossProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額（粗利益・利益率）.
        /// </summary>
        public static string lblAmountGrossProfitRate {
            get {
                return ResourceManager.GetString("lblAmountGrossProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額（支払）.
        /// </summary>
        public static string lblAmountPayment {
            get {
                return ResourceManager.GetString("lblAmountPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額（支払・消費税率）.
        /// </summary>
        public static string lblAmountPaymentConsumptionTax {
            get {
                return ResourceManager.GetString("lblAmountPaymentConsumptionTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額（売上）.
        /// </summary>
        public static string lblAmountSale {
            get {
                return ResourceManager.GetString("lblAmountSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額（売上・消費税率）.
        /// </summary>
        public static string lblAmountSaleConsumptionTax {
            get {
                return ResourceManager.GetString("lblAmountSaleConsumptionTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書送付先.
        /// </summary>
        public static string lblBillingAddress {
            get {
                return ResourceManager.GetString("lblBillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求精算額.
        /// </summary>
        public static string lblBillingAdjustedAmount {
            get {
                return ResourceManager.GetString("lblBillingAdjustedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求精算時間.
        /// </summary>
        public static string lblBillingAdjustedTime {
            get {
                return ResourceManager.GetString("lblBillingAdjustedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求調整額.
        /// </summary>
        public static string lblBillingAdjustment {
            get {
                return ResourceManager.GetString("lblBillingAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求金額.
        /// </summary>
        public static string lblBillingAmount {
            get {
                return ResourceManager.GetString("lblBillingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税込請求額.
        /// </summary>
        public static string lblBillingAmountTaxIncluded {
            get {
                return ResourceManager.GetString("lblBillingAmountTaxIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求締日.
        /// </summary>
        public static string lblBillingClosingDay {
            get {
                return ResourceManager.GetString("lblBillingClosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求共有メモ.
        /// </summary>
        public static string lblBillingCommonMemo {
            get {
                return ResourceManager.GetString("lblBillingCommonMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string lblBillingDestination {
            get {
                return ResourceManager.GetString("lblBillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先（企業名）.
        /// </summary>
        public static string lblBillingDestinationCompanyName {
            get {
                return ResourceManager.GetString("lblBillingDestinationCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先（担当者名）.
        /// </summary>
        public static string lblBillingDestinationPICName {
            get {
                return ResourceManager.GetString("lblBillingDestinationPICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求情報.
        /// </summary>
        public static string lblBillingInfo {
            get {
                return ResourceManager.GetString("lblBillingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求稼働時間.
        /// </summary>
        public static string lblBillingOperatingTime {
            get {
                return ResourceManager.GetString("lblBillingOperatingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求諸経費（その他）.
        /// </summary>
        public static string lblBillingOverHeadCostOther {
            get {
                return ResourceManager.GetString("lblBillingOverHeadCostOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求諸経費（交通費）.
        /// </summary>
        public static string lblBillingOverHeadCostTranspostationExpense {
            get {
                return ResourceManager.GetString("lblBillingOverHeadCostTranspostationExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求ルール.
        /// </summary>
        public static string lblBillingRules {
            get {
                return ResourceManager.GetString("lblBillingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求合計.
        /// </summary>
        public static string lblBillingTotal {
            get {
                return ResourceManager.GetString("lblBillingTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社内共有情報.
        /// </summary>
        public static string lblCompanyInternalCommonInfo {
            get {
                return ResourceManager.GetString("lblCompanyInternalCommonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認日時.
        /// </summary>
        public static string lblConfirmDateTime {
            get {
                return ResourceManager.GetString("lblConfirmDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約情報.
        /// </summary>
        public static string lblContractInfo {
            get {
                return ResourceManager.GetString("lblContractInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客先フォーマット.
        /// </summary>
        public static string lblCustomerDestinationFormat {
            get {
                return ResourceManager.GetString("lblCustomerDestinationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日時.
        /// </summary>
        public static string lblDateTime {
            get {
                return ResourceManager.GetString("lblDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ送信日時.
        /// </summary>
        public static string lblDateTimeSendData {
            get {
                return ResourceManager.GetString("lblDateTimeSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原本送付日時.
        /// </summary>
        public static string lblDateTimeSendOriginalCopy {
            get {
                return ResourceManager.GetString("lblDateTimeSendOriginalCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引落先口座情報.
        /// </summary>
        public static string lblDepositAccountInfo {
            get {
                return ResourceManager.GetString("lblDepositAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間.
        /// </summary>
        public static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求時間幅.
        /// </summary>
        public static string lblDurationTimeBilling {
            get {
                return ResourceManager.GetString("lblDurationTimeBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求時間幅（控除）.
        /// </summary>
        public static string lblDurationTimeBillingDeduction {
            get {
                return ResourceManager.GetString("lblDurationTimeBillingDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求時間幅（超過）.
        /// </summary>
        public static string lblDurationTimeBillingExcess {
            get {
                return ResourceManager.GetString("lblDurationTimeBillingExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求時間幅（上限）.
        /// </summary>
        public static string lblDurationTimeBillingMax {
            get {
                return ResourceManager.GetString("lblDurationTimeBillingMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求時間幅（下限）.
        /// </summary>
        public static string lblDurationTimeBillingMin {
            get {
                return ResourceManager.GetString("lblDurationTimeBillingMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払時間幅.
        /// </summary>
        public static string lblDurationTimePayment {
            get {
                return ResourceManager.GetString("lblDurationTimePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払時間幅（控除）.
        /// </summary>
        public static string lblDurationTimePaymentDeduction {
            get {
                return ResourceManager.GetString("lblDurationTimePaymentDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払時間幅（超過）.
        /// </summary>
        public static string lblDurationTimePaymentExcess {
            get {
                return ResourceManager.GetString("lblDurationTimePaymentExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払時間幅（上限）.
        /// </summary>
        public static string lblDurationTimePaymentMax {
            get {
                return ResourceManager.GetString("lblDurationTimePaymentMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払時間幅（下限）.
        /// </summary>
        public static string lblDurationTimePaymentMin {
            get {
                return ResourceManager.GetString("lblDurationTimePaymentMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最終更新者.
        /// </summary>
        public static string lblFinalUpdatePerson {
            get {
                return ResourceManager.GetString("lblFinalUpdatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求諸経費含む.
        /// </summary>
        public static string lblIncludeBillingOverCost {
            get {
                return ResourceManager.GetString("lblIncludeBillingOverCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払諸経費含む.
        /// </summary>
        public static string lblIncludePaymentOverCost {
            get {
                return ResourceManager.GetString("lblIncludePaymentOverCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書発行日付.
        /// </summary>
        public static string lblIssueDebitNoteDate {
            get {
                return ResourceManager.GetString("lblIssueDebitNoteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備考.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稼働時間.
        /// </summary>
        public static string lblOperateTime {
            get {
                return ResourceManager.GetString("lblOperateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先.
        /// </summary>
        public static string lblPayentDestination {
            get {
                return ResourceManager.GetString("lblPayentDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払精算額.
        /// </summary>
        public static string lblPaymentAdjustedAmount {
            get {
                return ResourceManager.GetString("lblPaymentAdjustedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払調整額.
        /// </summary>
        public static string lblPaymentAdjustmentAmount {
            get {
                return ResourceManager.GetString("lblPaymentAdjustmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払金額.
        /// </summary>
        public static string lblPaymentAmount {
            get {
                return ResourceManager.GetString("lblPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税込支払額.
        /// </summary>
        public static string lblPaymentAmountTaxIncluded {
            get {
                return ResourceManager.GetString("lblPaymentAmountTaxIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払締日.
        /// </summary>
        public static string lblPaymentClosingDay {
            get {
                return ResourceManager.GetString("lblPaymentClosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払日.
        /// </summary>
        public static string lblPaymentDate {
            get {
                return ResourceManager.GetString("lblPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先（企業名）.
        /// </summary>
        public static string lblPaymentDestinationCompanyName {
            get {
                return ResourceManager.GetString("lblPaymentDestinationCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先（担当者名）.
        /// </summary>
        public static string lblPaymentDestinationPICName {
            get {
                return ResourceManager.GetString("lblPaymentDestinationPICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払情報.
        /// </summary>
        public static string lblPaymentInfo {
            get {
                return ResourceManager.GetString("lblPaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払稼働時間.
        /// </summary>
        public static string lblPaymentOperateTime {
            get {
                return ResourceManager.GetString("lblPaymentOperateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払諸経費（その他）.
        /// </summary>
        public static string lblPaymentOverHeadCostOther {
            get {
                return ResourceManager.GetString("lblPaymentOverHeadCostOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払諸経費（交通費）.
        /// </summary>
        public static string lblPaymentOverHeadCostTranspostationExpense {
            get {
                return ResourceManager.GetString("lblPaymentOverHeadCostTranspostationExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払合計.
        /// </summary>
        public static string lblPaymentTotal {
            get {
                return ResourceManager.GetString("lblPaymentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払単価.
        /// </summary>
        public static string lblPaymentUnitPrice {
            get {
                return ResourceManager.GetString("lblPaymentUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払精算時間.
        /// </summary>
        public static string lblPaymetnAdjustedTime {
            get {
                return ResourceManager.GetString("lblPaymetnAdjustedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者.
        /// </summary>
        public static string lblPIC {
            get {
                return ResourceManager.GetString("lblPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者（顧客先）.
        /// </summary>
        public static string lblPICCustomer {
            get {
                return ResourceManager.GetString("lblPICCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者（外注先）.
        /// </summary>
        public static string lblPICOutSourceDestination {
            get {
                return ResourceManager.GetString("lblPICOutSourceDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string lblProjectName {
            get {
                return ResourceManager.GetString("lblProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金日.
        /// </summary>
        public static string lblReceiveMoneyDate {
            get {
                return ResourceManager.GetString("lblReceiveMoneyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金状況.
        /// </summary>
        public static string lblReceiveMoneyStatus {
            get {
                return ResourceManager.GetString("lblReceiveMoneyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回収方法.
        /// </summary>
        public static string lblRecoveryMethod {
            get {
                return ResourceManager.GetString("lblRecoveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送付リミット.
        /// </summary>
        public static string lblSendLimit {
            get {
                return ResourceManager.GetString("lblSendLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間単位.
        /// </summary>
        public static string lblTimeUnit {
            get {
                return ResourceManager.GetString("lblTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求個別入力.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振込先.
        /// </summary>
        public static string lblTransferDestination {
            get {
                return ResourceManager.GetString("lblTransferDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単価請求額.
        /// </summary>
        public static string lblUnitCostBillingAmount {
            get {
                return ResourceManager.GetString("lblUnitCostBillingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業者／品名.
        /// </summary>
        public static string lblWorkerProductName {
            get {
                return ResourceManager.GetString("lblWorkerProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業場所.
        /// </summary>
        public static string lblWorkPlace {
            get {
                return ResourceManager.GetString("lblWorkPlace", resourceCulture);
            }
        }
    }
}
