//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillingNumberList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillingNumberList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.BillingNumberList", typeof(BillingNumberList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一覧の内容をCSV出力.
        /// </summary>
        public static string btnOutputCSV {
            get {
                return ResourceManager.GetString("btnOutputCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約企業名.
        /// </summary>
        public static string lblContractCompanyName {
            get {
                return ResourceManager.GetString("lblContractCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約請求件数一覧.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求データ件数（翌月）.
        /// </summary>
        public static string TH_BillingNumberDataNextMonth {
            get {
                return ResourceManager.GetString("TH_BillingNumberDataNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求データ件数（先月）.
        /// </summary>
        public static string TH_BillingNumberDataPrevMonth {
            get {
                return ResourceManager.GetString("TH_BillingNumberDataPrevMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求データ件数（当月）.
        /// </summary>
        public static string TH_BillingNumberDataThisMonth {
            get {
                return ResourceManager.GetString("TH_BillingNumberDataThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約企業名.
        /// </summary>
        public static string TH_ContractCompanyName {
            get {
                return ResourceManager.GetString("TH_ContractCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ご契約プラン名.
        /// </summary>
        public static string TH_ContractPlanName {
            get {
                return ResourceManager.GetString("TH_ContractPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロードファイル容量.
        /// </summary>
        public static string TH_FileSizeTotal {
            get {
                return ResourceManager.GetString("TH_FileSizeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ最大件数.
        /// </summary>
        public static string TH_MaximumNumberData {
            get {
                return ResourceManager.GetString("TH_MaximumNumberData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string TH_SerialNumber {
            get {
                return ResourceManager.GetString("TH_SerialNumber", resourceCulture);
            }
        }
    }
}
