//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContractFinish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContractFinish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.ContractFinish", typeof(ContractFinish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約通り.
        /// </summary>
        public static string AsContracted {
            get {
                return ResourceManager.GetString("AsContracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        public static string btnFinish {
            get {
                return ResourceManager.GetString("btnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string ClaimDestination {
            get {
                return ResourceManager.GetString("ClaimDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別分類.
        /// </summary>
        public static string ContractSubType {
            get {
                return ResourceManager.GetString("ContractSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客先担当部署.
        /// </summary>
        public static string CustomerInchargeDepartment {
            get {
                return ResourceManager.GetString("CustomerInchargeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客先担当者名.
        /// </summary>
        public static string CustomerPICName {
            get {
                return ResourceManager.GetString("CustomerPICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了日.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了条件.
        /// </summary>
        public static string FinishCondition {
            get {
                return ResourceManager.GetString("FinishCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 様.
        /// </summary>
        public static string lblMister {
            get {
                return ResourceManager.GetString("lblMister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間なし.
        /// </summary>
        public static string NoPaymentTime {
            get {
                return ResourceManager.GetString("NoPaymentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間なし.
        /// </summary>
        public static string NoReceivedTime {
            get {
                return ResourceManager.GetString("NoReceivedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備考.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外注先担当部署.
        /// </summary>
        public static string OutsourcingCompanyDepartment {
            get {
                return ResourceManager.GetString("OutsourcingCompanyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外注先担当者名.
        /// </summary>
        public static string OutsourcingCompanyPICName {
            get {
                return ResourceManager.GetString("OutsourcingCompanyPICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 払い.
        /// </summary>
        public static string PaymentAmount {
            get {
                return ResourceManager.GetString("PaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先.
        /// </summary>
        public static string PaymentDestination {
            get {
                return ResourceManager.GetString("PaymentDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 払い基準時間上限.
        /// </summary>
        public static string PaymentStandardTimeMax {
            get {
                return ResourceManager.GetString("PaymentStandardTimeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 払い基準時間下限.
        /// </summary>
        public static string PaymentStandardTimeMin {
            get {
                return ResourceManager.GetString("PaymentStandardTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 払い課税.
        /// </summary>
        public static string PaymentTaxation {
            get {
                return ResourceManager.GetString("PaymentTaxation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 払い税率.
        /// </summary>
        public static string PaymentTaxRate {
            get {
                return ResourceManager.GetString("PaymentTaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製品.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 途中終了.
        /// </summary>
        public static string raEndMiddleContract {
            get {
                return ResourceManager.GetString("raEndMiddleContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約通り.
        /// </summary>
        public static string raFollowContract {
            get {
                return ResourceManager.GetString("raFollowContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 途中終了＋特殊精算.
        /// </summary>
        public static string raMiddleContractAndSpecialPayment {
            get {
                return ResourceManager.GetString("raMiddleContractAndSpecialPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け.
        /// </summary>
        public static string ReceivedAmount {
            get {
                return ResourceManager.GetString("ReceivedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け基準時間上限.
        /// </summary>
        public static string ReceiveStandardTimeMax {
            get {
                return ResourceManager.GetString("ReceiveStandardTimeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間帯.
        /// </summary>
        public static string ReceiveStandardTimeMin {
            get {
                return ResourceManager.GetString("ReceiveStandardTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け課税.
        /// </summary>
        public static string ReceiveTaxation {
            get {
                return ResourceManager.GetString("ReceiveTaxation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け税率.
        /// </summary>
        public static string ReceiveTaxRate {
            get {
                return ResourceManager.GetString("ReceiveTaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 途中終了.
        /// </summary>
        public static string TerminatedMiddle {
            get {
                return ResourceManager.GetString("TerminatedMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 途中終了＋特殊精算.
        /// </summary>
        public static string TerminatedMiddleAndSpecialPayment {
            get {
                return ResourceManager.GetString("TerminatedMiddleAndSpecialPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約終了.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業者.
        /// </summary>
        public static string WorkerName {
            get {
                return ResourceManager.GetString("WorkerName", resourceCulture);
            }
        }
    }
}
