//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContractList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContractList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.ContractList", typeof(ContractList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string BillingDestination {
            get {
                return ResourceManager.GetString("BillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全チェック.
        /// </summary>
        public static string btnCheckAllEstimate {
            get {
                return ResourceManager.GetString("btnCheckAllEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当月契約終了予定案件をCSV出力.
        /// </summary>
        public static string btnExportCsv {
            get {
                return ResourceManager.GetString("btnExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書発行.
        /// </summary>
        public static string btnIssueEstimations {
            get {
                return ResourceManager.GetString("btnIssueEstimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注文書発行.
        /// </summary>
        public static string btnIssueOrders {
            get {
                return ResourceManager.GetString("btnIssueOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        public static string btnNewContract {
            get {
                return ResourceManager.GetString("btnNewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全チェック解除.
        /// </summary>
        public static string btnUnCheckAllEstimate {
            get {
                return ResourceManager.GetString("btnUnCheckAllEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約状況.
        /// </summary>
        public static string ContractStatus {
            get {
                return ResourceManager.GetString("ContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別分類.
        /// </summary>
        public static string ContractTypeClass {
            get {
                return ResourceManager.GetString("ContractTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客先担当部署.
        /// </summary>
        public static string CustomerDestinationDepartment {
            get {
                return ResourceManager.GetString("CustomerDestinationDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客先担当者名.
        /// </summary>
        public static string CustomerPICName {
            get {
                return ResourceManager.GetString("CustomerPICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書発行済みのデータが存在します。\n請求書を再作成する必要があります。宜しいですか？.
        /// </summary>
        public static string DeleteMessConfirm {
            get {
                return ResourceManager.GetString("DeleteMessConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に入金済みの請求が存在しているため、契約を削除できません.
        /// </summary>
        public static string DeleteMessInvalid {
            get {
                return ResourceManager.GetString("DeleteMessInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書一括発行.
        /// </summary>
        public static string IssuedEstimatePackage {
            get {
                return ResourceManager.GetString("IssuedEstimatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書発行.
        /// </summary>
        public static string IssueEstimate {
            get {
                return ResourceManager.GetString("IssueEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外注先担当者名.
        /// </summary>
        public static string OutsourcingPICName {
            get {
                return ResourceManager.GetString("OutsourcingPICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先.
        /// </summary>
        public static string PaymentDestination {
            get {
                return ResourceManager.GetString("PaymentDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製品.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検収日.
        /// </summary>
        public static string raAcceptanceDate {
            get {
                return ResourceManager.GetString("raAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品日.
        /// </summary>
        public static string raDeliveryDate {
            get {
                return ResourceManager.GetString("raDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間（終了）.
        /// </summary>
        public static string raEndDate {
            get {
                return ResourceManager.GetString("raEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件参画日.
        /// </summary>
        public static string raParticipationDate {
            get {
                return ResourceManager.GetString("raParticipationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間（開始）.
        /// </summary>
        public static string raStartDate {
            get {
                return ResourceManager.GetString("raStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書送付.
        /// </summary>
        public static string SendEstimate {
            get {
                return ResourceManager.GetString("SendEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外注先担当部署.
        /// </summary>
        public static string SubcontractorDepartment {
            get {
                return ResourceManager.GetString("SubcontractorDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 払い金額.
        /// </summary>
        public static string TH_AmountPayment {
            get {
                return ResourceManager.GetString("TH_AmountPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け金額.
        /// </summary>
        public static string TH_AmountReceived {
            get {
                return ResourceManager.GetString("TH_AmountReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要注意.
        /// </summary>
        public static string TH_Attention {
            get {
                return ResourceManager.GetString("TH_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string TH_BillingDestination {
            get {
                return ResourceManager.GetString("TH_BillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string TH_ContractType {
            get {
                return ResourceManager.GetString("TH_ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客先担当.
        /// </summary>
        public static string TH_CustomerPIC {
            get {
                return ResourceManager.GetString("TH_CustomerPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string TH_Delete {
            get {
                return ResourceManager.GetString("TH_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        public static string TH_EditContract {
            get {
                return ResourceManager.GetString("TH_EditContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        public static string TH_EndContract {
            get {
                return ResourceManager.GetString("TH_EndContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約終了日.
        /// </summary>
        public static string TH_EndDate {
            get {
                return ResourceManager.GetString("TH_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書発行日.
        /// </summary>
        public static string TH_EstimateIssueDate {
            get {
                return ResourceManager.GetString("TH_EstimateIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書送付日.
        /// </summary>
        public static string TH_EstimateSendDate {
            get {
                return ResourceManager.GetString("TH_EstimateSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 延長.
        /// </summary>
        public static string TH_ExtendContract {
            get {
                return ResourceManager.GetString("TH_ExtendContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 決定.
        /// </summary>
        public static string TH_NewContract {
            get {
                return ResourceManager.GetString("TH_NewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外注先担当.
        /// </summary>
        public static string TH_OutsourcingPIC {
            get {
                return ResourceManager.GetString("TH_OutsourcingPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先.
        /// </summary>
        public static string TH_PaymentDestination {
            get {
                return ResourceManager.GetString("TH_PaymentDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string TH_ProjectName {
            get {
                return ResourceManager.GetString("TH_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件参画日.
        /// </summary>
        public static string TH_ProjectParticipationDate {
            get {
                return ResourceManager.GetString("TH_ProjectParticipationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送付.
        /// </summary>
        public static string TH_SendEstimate {
            get {
                return ResourceManager.GetString("TH_SendEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約開始日.
        /// </summary>
        public static string TH_StartDate {
            get {
                return ResourceManager.GetString("TH_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示.
        /// </summary>
        public static string TH_ViewContract {
            get {
                return ResourceManager.GetString("TH_ViewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業者／品名.
        /// </summary>
        public static string TH_WorkerProduct {
            get {
                return ResourceManager.GetString("TH_WorkerProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約一覧.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業者／品名.
        /// </summary>
        public static string WorkerProductName {
            get {
                return ResourceManager.GetString("WorkerProductName", resourceCulture);
            }
        }
    }
}
