//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoverLetter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoverLetter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.CoverLetter", typeof(CoverLetter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択を一括作成.
        /// </summary>
        public static string btnCreateManyCoverLetter {
            get {
                return ResourceManager.GetString("btnCreateManyCoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書類送付状.
        /// </summary>
        public static string createTypeDocument {
            get {
                return ResourceManager.GetString("createTypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封筒住所.
        /// </summary>
        public static string createTypeEnvelopeAddress {
            get {
                return ResourceManager.GetString("createTypeEnvelopeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX送付状.
        /// </summary>
        public static string createTypeFax {
            get {
                return ResourceManager.GetString("createTypeFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01.
        /// </summary>
        public static string firstSheet {
            get {
                return ResourceManager.GetString("firstSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書類送付状フォーマットが設定されていません。.
        /// </summary>
        public static string formatPathByDocumentIsEmpty {
            get {
                return ResourceManager.GetString("formatPathByDocumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封筒住所フォーマットが設定されていません。.
        /// </summary>
        public static string formatPathByEnvelopeAddressIsEmpty {
            get {
                return ResourceManager.GetString("formatPathByEnvelopeAddressIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX送付状フォーマットが設定されていません。.
        /// </summary>
        public static string formatPathByFaxIsEmpty {
            get {
                return ResourceManager.GetString("formatPathByFaxIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成.
        /// </summary>
        public static string lbCreateCoverLetter {
            get {
                return ResourceManager.GetString("lbCreateCoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成種類.
        /// </summary>
        public static string lbCreateType {
            get {
                return ResourceManager.GetString("lbCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先名.
        /// </summary>
        public static string lblCustomer {
            get {
                return ResourceManager.GetString("lblCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所.
        /// </summary>
        public static string lblCustomerAddress {
            get {
                return ResourceManager.GetString("lblCustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先名(カナ).
        /// </summary>
        public static string lblCustomerKana {
            get {
                return ResourceManager.GetString("lblCustomerKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送付状を作成します。よろしいですか？.
        /// </summary>
        public static string msgConfirmCreate {
            get {
                return ResourceManager.GetString("msgConfirmCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書類送付状_.
        /// </summary>
        public static string outputFileByDocument {
            get {
                return ResourceManager.GetString("outputFileByDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封筒住所_.
        /// </summary>
        public static string outputFileByEnvelopeAddress {
            get {
                return ResourceManager.GetString("outputFileByEnvelopeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX送付状_.
        /// </summary>
        public static string outputFileByFax {
            get {
                return ResourceManager.GetString("outputFileByFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〒.
        /// </summary>
        public static string symbolZipCode {
            get {
                return ResourceManager.GetString("symbolZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所１.
        /// </summary>
        public static string TH_Address1 {
            get {
                return ResourceManager.GetString("TH_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所２.
        /// </summary>
        public static string TH_Address2 {
            get {
                return ResourceManager.GetString("TH_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個別作成.
        /// </summary>
        public static string TH_CreateCoverLetter {
            get {
                return ResourceManager.GetString("TH_CreateCoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先.
        /// </summary>
        public static string TH_Customer {
            get {
                return ResourceManager.GetString("TH_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX.
        /// </summary>
        public static string TH_Fax {
            get {
                return ResourceManager.GetString("TH_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部署名.
        /// </summary>
        public static string TH_Group {
            get {
                return ResourceManager.GetString("TH_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備考.
        /// </summary>
        public static string TH_Note {
            get {
                return ResourceManager.GetString("TH_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者.
        /// </summary>
        public static string TH_PIC {
            get {
                return ResourceManager.GetString("TH_PIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 役職名.
        /// </summary>
        public static string TH_Position {
            get {
                return ResourceManager.GetString("TH_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〒.
        /// </summary>
        public static string TH_PostalCode {
            get {
                return ResourceManager.GetString("TH_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号.
        /// </summary>
        public static string TH_Telephone {
            get {
                return ResourceManager.GetString("TH_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送付状作成.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
