//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerRegister {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerRegister() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.CustomerRegister", typeof(CustomerRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加の住所.
        /// </summary>
        public static string AdditionalAddress {
            get {
                return ResourceManager.GetString("AdditionalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所1.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先住所情報.
        /// </summary>
        public static string AddressPopupTitle {
            get {
                return ResourceManager.GetString("AddressPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所識別名.
        /// </summary>
        public static string AddressUniqueName {
            get {
                return ResourceManager.GetString("AddressUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 業種.
        /// </summary>
        public static string biz_category {
            get {
                return ResourceManager.GetString("biz_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所検索.
        /// </summary>
        public static string btnSearchAddress {
            get {
                return ResourceManager.GetString("btnSearchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資本金.
        /// </summary>
        public static string capital {
            get {
                return ResourceManager.GetString("capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業名（表示名）.
        /// </summary>
        public static string CustomerDisplayName {
            get {
                return ResourceManager.GetString("CustomerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業名.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業名（カナ）.
        /// </summary>
        public static string CustomerNameKata {
            get {
                return ResourceManager.GetString("CustomerNameKata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無効.
        /// </summary>
        public static string DISABLE {
            get {
                return ResourceManager.GetString("DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX番号.
        /// </summary>
        public static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成者.
        /// </summary>
        public static string lblCreatedBy {
            get {
                return ResourceManager.GetString("lblCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成日.
        /// </summary>
        public static string lblCreatedDate {
            get {
                return ResourceManager.GetString("lblCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新者.
        /// </summary>
        public static string lblUpdatedBy {
            get {
                return ResourceManager.GetString("lblUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日.
        /// </summary>
        public static string lblUpdatedDate {
            get {
                return ResourceManager.GetString("lblUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※カブシキガイシャ・ユウゲンガイシャはカナとして入力しないでください.
        /// </summary>
        public static string msgCompanyNameNoKana {
            get {
                return ResourceManager.GetString("msgCompanyNameNoKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加の住所を入力.
        /// </summary>
        public static string msgInputAdress {
            get {
                return ResourceManager.GetString("msgInputAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備考.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社員数.
        /// </summary>
        public static string num_employees {
            get {
                return ResourceManager.GetString("num_employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状態.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先情報.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
    }
}
