//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DebitAccountInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebitAccountInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.DebitAccountInfo", typeof(DebitAccountInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 口座名義人.
        /// </summary>
        public static string lblBankAccountHolder {
            get {
                return ResourceManager.GetString("lblBankAccountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 口座番号.
        /// </summary>
        public static string lblBankAccountNumber {
            get {
                return ResourceManager.GetString("lblBankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 口座種別.
        /// </summary>
        public static string lblBankAccountType {
            get {
                return ResourceManager.GetString("lblBankAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 銀行用管理コード.
        /// </summary>
        public static string lblBankManagementCode {
            get {
                return ResourceManager.GetString("lblBankManagementCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金融機関コード.
        /// </summary>
        public static string lblBankOrgCode {
            get {
                return ResourceManager.GetString("lblBankOrgCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金融機関名.
        /// </summary>
        public static string lblBankOrgName {
            get {
                return ResourceManager.GetString("lblBankOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金融機関支店コード.
        /// </summary>
        public static string lblBranchBankOrgCode {
            get {
                return ResourceManager.GetString("lblBranchBankOrgCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金融機関支店名.
        /// </summary>
        public static string lblBranchBankOrgName {
            get {
                return ResourceManager.GetString("lblBranchBankOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当座預金.
        /// </summary>
        public static string lblCurrentAccount {
            get {
                return ResourceManager.GetString("lblCurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通預金.
        /// </summary>
        public static string lblDepositAccount {
            get {
                return ResourceManager.GetString("lblDepositAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他.
        /// </summary>
        public static string lblOthersAccount {
            get {
                return ResourceManager.GetString("lblOthersAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 貯蓄預金.
        /// </summary>
        public static string lblSavedAccount {
            get {
                return ResourceManager.GetString("lblSavedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引落先口座情報.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
