//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EstimationStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EstimationStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.EstimationStatus", typeof(EstimationStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約変更.
        /// </summary>
        public static string ChangeContract {
            get {
                return ResourceManager.GetString("ChangeContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約作成.
        /// </summary>
        public static string CreateContract {
            get {
                return ResourceManager.GetString("CreateContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積作成.
        /// </summary>
        public static string CreateEstimate {
            get {
                return ResourceManager.GetString("CreateEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約削除.
        /// </summary>
        public static string DeleteContract {
            get {
                return ResourceManager.GetString("DeleteContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積削除.
        /// </summary>
        public static string DeleteEstimate {
            get {
                return ResourceManager.GetString("DeleteEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積編集.
        /// </summary>
        public static string EditEstimate {
            get {
                return ResourceManager.GetString("EditEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求終了.
        /// </summary>
        public static string FinishBilling {
            get {
                return ResourceManager.GetString("FinishBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求終了（延長継続）.
        /// </summary>
        public static string FinishBillingExtensionContinues {
            get {
                return ResourceManager.GetString("FinishBillingExtensionContinues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求終了（途中終了）.
        /// </summary>
        public static string FinishBillingFinishInMiddle {
            get {
                return ResourceManager.GetString("FinishBillingFinishInMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全終了.
        /// </summary>
        public static string FinishComplete {
            get {
                return ResourceManager.GetString("FinishComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 延長終了.
        /// </summary>
        public static string FinishExpand {
            get {
                return ResourceManager.GetString("FinishExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 途中終了.
        /// </summary>
        public static string FinishInMiddle {
            get {
                return ResourceManager.GetString("FinishInMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件終了.
        /// </summary>
        public static string FinishProject {
            get {
                return ResourceManager.GetString("FinishProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約決定.
        /// </summary>
        public static string ImplementContract {
            get {
                return ResourceManager.GetString("ImplementContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積発行.
        /// </summary>
        public static string IssueEstimate {
            get {
                return ResourceManager.GetString("IssueEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積再発行.
        /// </summary>
        public static string ReissueEstimate {
            get {
                return ResourceManager.GetString("ReissueEstimate", resourceCulture);
            }
        }
    }
}
