//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EstimationRegister {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EstimationRegister() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.EstimationRegister", typeof(EstimationRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検収日.
        /// </summary>
        public static string AcceptanceDate {
            get {
                return ResourceManager.GetString("AcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添付ファイル.
        /// </summary>
        public static string AttachedFile {
            get {
                return ResourceManager.GetString("AttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基準時間下限.
        /// </summary>
        public static string BaseTimeLower {
            get {
                return ResourceManager.GetString("BaseTimeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基準時間上限.
        /// </summary>
        public static string BaseTimeUpper {
            get {
                return ResourceManager.GetString("BaseTimeUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        public static string btnAddProduct {
            get {
                return ResourceManager.GetString("btnAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添付.
        /// </summary>
        public static string btnAttach {
            get {
                return ResourceManager.GetString("btnAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算.
        /// </summary>
        public static string btnCalculation {
            get {
                return ResourceManager.GetString("btnCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添付削除.
        /// </summary>
        public static string btnDeleteAttach {
            get {
                return ResourceManager.GetString("btnDeleteAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書発行.
        /// </summary>
        public static string btnIssueEstimate {
            get {
                return ResourceManager.GetString("btnIssueEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注文書発行.
        /// </summary>
        public static string btnIssueOrder {
            get {
                return ResourceManager.GetString("btnIssueOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        public static string btnSelectCustomer {
            get {
                return ResourceManager.GetString("btnSelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 締日.
        /// </summary>
        public static string ClosingDate {
            get {
                return ResourceManager.GetString("ClosingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 締月.
        /// </summary>
        public static string ClosingSite {
            get {
                return ResourceManager.GetString("ClosingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コメント.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共有メモ.
        /// </summary>
        public static string CommonMemo {
            get {
                return ResourceManager.GetString("CommonMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自社担当.
        /// </summary>
        public static string CompanyInCharge {
            get {
                return ResourceManager.GetString("CompanyInCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消費税額.
        /// </summary>
        public static string ConsumptionTax {
            get {
                return ResourceManager.GetString("ConsumptionTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間.
        /// </summary>
        public static string ContractDuration {
            get {
                return ResourceManager.GetString("ContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別カテゴリ.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別サブカテゴリ.
        /// </summary>
        public static string ContractTypeSub {
            get {
                return ResourceManager.GetString("ContractTypeSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先企業.
        /// </summary>
        public static string CustomerCompany {
            get {
                return ResourceManager.GetString("CustomerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 発行日.
        /// </summary>
        public static string DateIssue {
            get {
                return ResourceManager.GetString("DateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 発行処理日.
        /// </summary>
        public static string DateProcessIssue {
            get {
                return ResourceManager.GetString("DateProcessIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送付処理日.
        /// </summary>
        public static string DateProcessSend {
            get {
                return ResourceManager.GetString("DateProcessSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控除単価.
        /// </summary>
        public static string DeductionUnitPrice {
            get {
                return ResourceManager.GetString("DeductionUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DefaultUnitQuantity {
            get {
                return ResourceManager.GetString("DefaultUnitQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string DefaultUnitTime {
            get {
                return ResourceManager.GetString("DefaultUnitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品物件.
        /// </summary>
        public static string Deliverable {
            get {
                return ResourceManager.GetString("Deliverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品場所.
        /// </summary>
        public static string DeliverPlace {
            get {
                return ResourceManager.GetString("DeliverPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品日.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積区分.
        /// </summary>
        public static string EstimateClassification {
            get {
                return ResourceManager.GetString("EstimateClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積条件.
        /// </summary>
        public static string EstimateCondition {
            get {
                return ResourceManager.GetString("EstimateCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積詳細.
        /// </summary>
        public static string EstimateDetail {
            get {
                return ResourceManager.GetString("EstimateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積金額合計.
        /// </summary>
        public static string EstimateMoneyAmountTotal {
            get {
                return ResourceManager.GetString("EstimateMoneyAmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積金額合計（税込）.
        /// </summary>
        public static string EstimateMoneyAmountTotalIncludeTax {
            get {
                return ResourceManager.GetString("EstimateMoneyAmountTotalIncludeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 課税対象額合計.
        /// </summary>
        public static string EstimateMoneyAmountTotalTaxable {
            get {
                return ResourceManager.GetString("EstimateMoneyAmountTotalTaxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積番号.
        /// </summary>
        public static string EstimateNumber {
            get {
                return ResourceManager.GetString("EstimateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積条件.
        /// </summary>
        public static string EstimationCondition {
            get {
                return ResourceManager.GetString("EstimationCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積番号接頭辞.
        /// </summary>
        public static string EstNoPrefix {
            get {
                return ResourceManager.GetString("EstNoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積番号年月.
        /// </summary>
        public static string EstNoYM {
            get {
                return ResourceManager.GetString("EstNoYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備考.
        /// </summary>
        public static string FileAttachedNote {
            get {
                return ResourceManager.GetString("FileAttachedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主担当部署.
        /// </summary>
        public static string MainInChargeDepartment {
            get {
                return ResourceManager.GetString("MainInChargeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主担当者名.
        /// </summary>
        public static string MainInChargeName {
            get {
                return ResourceManager.GetString("MainInChargeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共有メモ.
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額.
        /// </summary>
        public static string MoneyAmount {
            get {
                return ResourceManager.GetString("MoneyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名.
        /// </summary>
        public static string Nomen {
            get {
                return ResourceManager.GetString("Nomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超過単価.
        /// </summary>
        public static string OvertimeUnitPrice {
            get {
                return ResourceManager.GetString("OvertimeUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一括/月額.
        /// </summary>
        public static string PackageMonth {
            get {
                return ResourceManager.GetString("PackageMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払日.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精算方法.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払サイト.
        /// </summary>
        public static string PaymentSite {
            get {
                return ResourceManager.GetString("PaymentSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 様.
        /// </summary>
        public static string PICMr {
            get {
                return ResourceManager.GetString("PICMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /【担当者】.
        /// </summary>
        public static string PICName {
            get {
                return ResourceManager.GetString("PICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製品.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件詳細名.
        /// </summary>
        public static string ProjectDetailName {
            get {
                return ResourceManager.GetString("ProjectDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件表示名.
        /// </summary>
        public static string ProjectDisplayName {
            get {
                return ResourceManager.GetString("ProjectDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基準時間区分.
        /// </summary>
        public static string StandartTimeClassification {
            get {
                return ResourceManager.GetString("StandartTimeClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基準時間上限.
        /// </summary>
        public static string StandartTimeMax {
            get {
                return ResourceManager.GetString("StandartTimeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基準時間下限.
        /// </summary>
        public static string StandartTimeMin {
            get {
                return ResourceManager.GetString("StandartTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象年月.
        /// </summary>
        public static string TargetYearMonth {
            get {
                return ResourceManager.GetString("TargetYearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 課税/非課税.
        /// </summary>
        public static string TaxOrUnTax {
            get {
                return ResourceManager.GetString("TaxOrUnTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消費税率.
        /// </summary>
        public static string TaxRate {
            get {
                return ResourceManager.GetString("TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間単位.
        /// </summary>
        public static string TimeUnit {
            get {
                return ResourceManager.GetString("TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積登録.
        /// </summary>
        public static string TitleEstimationRegister {
            get {
                return ResourceManager.GetString("TitleEstimationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積作成.
        /// </summary>
        public static string TitleNew {
            get {
                return ResourceManager.GetString("TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積更新.
        /// </summary>
        public static string TitleUpdate {
            get {
                return ResourceManager.GetString("TitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積表示.
        /// </summary>
        public static string TitleView {
            get {
                return ResourceManager.GetString("TitleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単位.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単価.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 割単位.
        /// </summary>
        public static string UnitSplit {
            get {
                return ResourceManager.GetString("UnitSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年月.
        /// </summary>
        public static string YearMonth {
            get {
                return ResourceManager.GetString("YearMonth", resourceCulture);
            }
        }
    }
}
