//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EstimationList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EstimationList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.EstimationList", typeof(EstimationList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検収日.
        /// </summary>
        public static string AcceptanceContractDate {
            get {
                return ResourceManager.GetString("AcceptanceContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書.
        /// </summary>
        public static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        public static string btnNewEstimate {
            get {
                return ResourceManager.GetString("btnNewEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先企業.
        /// </summary>
        public static string btnSelectCustomer {
            get {
                return ResourceManager.GetString("btnSelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一括発行.
        /// </summary>
        public static string BulkIssue {
            get {
                return ResourceManager.GetString("BulkIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当部署.
        /// </summary>
        public static string ChargeDepartment {
            get {
                return ResourceManager.GetString("ChargeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別分類.
        /// </summary>
        public static string ContractTypeClass {
            get {
                return ResourceManager.GetString("ContractTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先企業.
        /// </summary>
        public static string CustomerCompany {
            get {
                return ResourceManager.GetString("CustomerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品日.
        /// </summary>
        public static string DeliveryContractDate {
            get {
                return ResourceManager.GetString("DeliveryContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間（終了）.
        /// </summary>
        public static string EndContractDate {
            get {
                return ResourceManager.GetString("EndContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積番号.
        /// </summary>
        public static string EstimateNo {
            get {
                return ResourceManager.GetString("EstimateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積区分.
        /// </summary>
        public static string EstimateType {
            get {
                return ResourceManager.GetString("EstimateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ｈ.
        /// </summary>
        public static string HourFullSize {
            get {
                return ResourceManager.GetString("HourFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 発行日.
        /// </summary>
        public static string IssueContractDate {
            get {
                return ResourceManager.GetString("IssueContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書発行.
        /// </summary>
        public static string IssueEstimate {
            get {
                return ResourceManager.GetString("IssueEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 様.
        /// </summary>
        public static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 御中.
        /// </summary>
        public static string Onchu {
            get {
                return ResourceManager.GetString("Onchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注文書.
        /// </summary>
        public static string OrderFile {
            get {
                return ResourceManager.GetString("OrderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者名.
        /// </summary>
        public static string PICName {
            get {
                return ResourceManager.GetString("PICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〒.
        /// </summary>
        public static string PostalMark {
            get {
                return ResourceManager.GetString("PostalMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製品.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検収日.
        /// </summary>
        public static string raAcceptanceDate {
            get {
                return ResourceManager.GetString("raAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品日.
        /// </summary>
        public static string raDeliveryDate {
            get {
                return ResourceManager.GetString("raDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間（終了）.
        /// </summary>
        public static string raEndDate {
            get {
                return ResourceManager.GetString("raEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 発行日.
        /// </summary>
        public static string raIssueDate {
            get {
                return ResourceManager.GetString("raIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間（開始）.
        /// </summary>
        public static string raStartDate {
            get {
                return ResourceManager.GetString("raStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書送付.
        /// </summary>
        public static string SendEstimate {
            get {
                return ResourceManager.GetString("SendEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間（開始）.
        /// </summary>
        public static string StartContractDate {
            get {
                return ResourceManager.GetString("StartContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検収日.
        /// </summary>
        public static string TH_AcceptanceDate {
            get {
                return ResourceManager.GetString("TH_AcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string TH_Category {
            get {
                return ResourceManager.GetString("TH_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別分類.
        /// </summary>
        public static string TH_CategorySubType {
            get {
                return ResourceManager.GetString("TH_CategorySubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区分.
        /// </summary>
        public static string TH_Classification {
            get {
                return ResourceManager.GetString("TH_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約.
        /// </summary>
        public static string TH_Contract {
            get {
                return ResourceManager.GetString("TH_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複製.
        /// </summary>
        public static string TH_Copy {
            get {
                return ResourceManager.GetString("TH_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先企業.
        /// </summary>
        public static string TH_CustomerCompanyName {
            get {
                return ResourceManager.GetString("TH_CustomerCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string TH_DeleteEstimate {
            get {
                return ResourceManager.GetString("TH_DeleteEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品日.
        /// </summary>
        public static string TH_DeliverDate {
            get {
                return ResourceManager.GetString("TH_DeliverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積金額.
        /// </summary>
        public static string TH_EstimateAmount {
            get {
                return ResourceManager.GetString("TH_EstimateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積番号.
        /// </summary>
        public static string TH_EstimateNo {
            get {
                return ResourceManager.GetString("TH_EstimateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追番.
        /// </summary>
        public static string TH_EstimateNoAdd {
            get {
                return ResourceManager.GetString("TH_EstimateNoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書.
        /// </summary>
        public static string TH_Estimation {
            get {
                return ResourceManager.GetString("TH_Estimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了日.
        /// </summary>
        public static string TH_FinishDate {
            get {
                return ResourceManager.GetString("TH_FinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 発行.
        /// </summary>
        public static string TH_Issue {
            get {
                return ResourceManager.GetString("TH_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 発行日.
        /// </summary>
        public static string TH_IssueDate {
            get {
                return ResourceManager.GetString("TH_IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製品.
        /// </summary>
        public static string TH_Product {
            get {
                return ResourceManager.GetString("TH_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string TH_ProjectName {
            get {
                return ResourceManager.GetString("TH_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再見積.
        /// </summary>
        public static string TH_ReEstimate {
            get {
                return ResourceManager.GetString("TH_ReEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送付.
        /// </summary>
        public static string TH_SendEstimate {
            get {
                return ResourceManager.GetString("TH_SendEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始日.
        /// </summary>
        public static string TH_StartDate {
            get {
                return ResourceManager.GetString("TH_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示.
        /// </summary>
        public static string TH_ViewEstimate {
            get {
                return ResourceManager.GetString("TH_ViewEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積一覧.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積情報一覧（契約）.
        /// </summary>
        public static string TitleForContract {
            get {
                return ResourceManager.GetString("TitleForContract", resourceCulture);
            }
        }
    }
}
