//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iEnterAsia.iseiQ.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EstimationRegister {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EstimationRegister() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iEnterAsia.iseiQ.Constants.Resources.EstimationRegister", typeof(EstimationRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検収日.
        /// </summary>
        public static string AcceptanceDate {
            get {
                return ResourceManager.GetString("AcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        public static string btnAddProduct {
            get {
                return ResourceManager.GetString("btnAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 発行.
        /// </summary>
        public static string btnIssue {
            get {
                return ResourceManager.GetString("btnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSelectCustomer {
            get {
                return ResourceManager.GetString("btnSelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 締日.
        /// </summary>
        public static string ClosingDate {
            get {
                return ResourceManager.GetString("ClosingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 締めサイト.
        /// </summary>
        public static string ClosingSite {
            get {
                return ResourceManager.GetString("ClosingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共有メモ.
        /// </summary>
        public static string CommonMemo {
            get {
                return ResourceManager.GetString("CommonMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間.
        /// </summary>
        public static string ContractDuration {
            get {
                return ResourceManager.GetString("ContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先企業.
        /// </summary>
        public static string CustomerCompany {
            get {
                return ResourceManager.GetString("CustomerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品日.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積区分.
        /// </summary>
        public static string EstimateClassification {
            get {
                return ResourceManager.GetString("EstimateClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積金額合計.
        /// </summary>
        public static string EstimateMoneyAmountTotal {
            get {
                return ResourceManager.GetString("EstimateMoneyAmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積番号.
        /// </summary>
        public static string EstimateNumber {
            get {
                return ResourceManager.GetString("EstimateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積条件.
        /// </summary>
        public static string EstimationCondition {
            get {
                return ResourceManager.GetString("EstimationCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金額.
        /// </summary>
        public static string MoneyAmount {
            get {
                return ResourceManager.GetString("MoneyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払日.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払サイト.
        /// </summary>
        public static string PaymentSite {
            get {
                return ResourceManager.GetString("PaymentSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件詳細名.
        /// </summary>
        public static string ProjectDetailName {
            get {
                return ResourceManager.GetString("ProjectDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件表示名.
        /// </summary>
        public static string ProjectDisplayName {
            get {
                return ResourceManager.GetString("ProjectDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積登録.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単位.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単価.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
    }
}
