//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExportSalesPayemtnsInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportSalesPayemtnsInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.ExportSalesPayemtnsInfo", typeof(ExportSalesPayemtnsInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて解除.
        /// </summary>
        public static string btnDeselectAll {
            get {
                return ResourceManager.GetString("btnDeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力.
        /// </summary>
        public static string btnExport {
            get {
                return ResourceManager.GetString("btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて選択.
        /// </summary>
        public static string btnSelectAll {
            get {
                return ResourceManager.GetString("btnSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求情報.
        /// </summary>
        public static string hdrBillingInfo {
            get {
                return ResourceManager.GetString("hdrBillingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約情報.
        /// </summary>
        public static string hdrContractInfo {
            get {
                return ResourceManager.GetString("hdrContractInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他.
        /// </summary>
        public static string hdrOtherInfo {
            get {
                return ResourceManager.GetString("hdrOtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払情報.
        /// </summary>
        public static string hdrPaymentInfo {
            get {
                return ResourceManager.GetString("hdrPaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け精算額.
        /// </summary>
        public static string lblBiAdjustedAmount {
            get {
                return ResourceManager.GetString("lblBiAdjustedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け精算時間.
        /// </summary>
        public static string lblBiAdjustedTime {
            get {
                return ResourceManager.GetString("lblBiAdjustedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求締日.
        /// </summary>
        public static string lblBiBillingClosingDay {
            get {
                return ResourceManager.GetString("lblBiBillingClosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string lblBiCustomer {
            get {
                return ResourceManager.GetString("lblBiCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先担当部署.
        /// </summary>
        public static string lblBiGroupName {
            get {
                return ResourceManager.GetString("lblBiGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求稼働時間.
        /// </summary>
        public static string lblBiOperateTime {
            get {
                return ResourceManager.GetString("lblBiOperateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け諸経費(その他).
        /// </summary>
        public static string lblBiOverHeadCostOthers {
            get {
                return ResourceManager.GetString("lblBiOverHeadCostOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け諸経費(交通費).
        /// </summary>
        public static string lblBiOverHeadCostTrans {
            get {
                return ResourceManager.GetString("lblBiOverHeadCostTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先担当者.
        /// </summary>
        public static string lblBiPicName {
            get {
                return ResourceManager.GetString("lblBiPicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け調整額.
        /// </summary>
        public static string lblBiReceivedAdjustment {
            get {
                return ResourceManager.GetString("lblBiReceivedAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金日.
        /// </summary>
        public static string lblBiReceiveDate {
            get {
                return ResourceManager.GetString("lblBiReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金予定日.
        /// </summary>
        public static string lblBiReceivePlanDate {
            get {
                return ResourceManager.GetString("lblBiReceivePlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け合計額.
        /// </summary>
        public static string lblBiTotalBillingAmount {
            get {
                return ResourceManager.GetString("lblBiTotalBillingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受け税込合計額.
        /// </summary>
        public static string lblBiTotalBillingAmountIncludeTax {
            get {
                return ResourceManager.GetString("lblBiTotalBillingAmountIncludeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単価請求額.
        /// </summary>
        public static string lblBiUnitPrice {
            get {
                return ResourceManager.GetString("lblBiUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string lblCtrCategory {
            get {
                return ResourceManager.GetString("lblCtrCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約終了日.
        /// </summary>
        public static string lblCtrEndDate {
            get {
                return ResourceManager.GetString("lblCtrEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稼働時間.
        /// </summary>
        public static string lblCtrOperateTime {
            get {
                return ResourceManager.GetString("lblCtrOperateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約開始日.
        /// </summary>
        public static string lblCtrStartDate {
            get {
                return ResourceManager.GetString("lblCtrStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 利益.
        /// </summary>
        public static string lblOtProfit {
            get {
                return ResourceManager.GetString("lblOtProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 利益率.
        /// </summary>
        public static string lblOtProfitRate {
            get {
                return ResourceManager.GetString("lblOtProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力項目指定.
        /// </summary>
        public static string lblOutputItemSpecification {
            get {
                return ResourceManager.GetString("lblOutputItemSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払精算額.
        /// </summary>
        public static string lblPmAdjustedAmount {
            get {
                return ResourceManager.GetString("lblPmAdjustedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払精算時間.
        /// </summary>
        public static string lblPmAdjustedTime {
            get {
                return ResourceManager.GetString("lblPmAdjustedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先.
        /// </summary>
        public static string lblPmCustomer {
            get {
                return ResourceManager.GetString("lblPmCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先担当部署.
        /// </summary>
        public static string lblPmGroupName {
            get {
                return ResourceManager.GetString("lblPmGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払稼働時間.
        /// </summary>
        public static string lblPmOperateTime {
            get {
                return ResourceManager.GetString("lblPmOperateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払諸経費(その他).
        /// </summary>
        public static string lblPmOverHeadCostOthers {
            get {
                return ResourceManager.GetString("lblPmOverHeadCostOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払諸経費(交通費).
        /// </summary>
        public static string lblPmOverHeadCostTrans {
            get {
                return ResourceManager.GetString("lblPmOverHeadCostTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払締日.
        /// </summary>
        public static string lblPmPaymentClosingDate {
            get {
                return ResourceManager.GetString("lblPmPaymentClosingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払日.
        /// </summary>
        public static string lblPmPaymentDate {
            get {
                return ResourceManager.GetString("lblPmPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払予定日.
        /// </summary>
        public static string lblPmPaymentPlanDate {
            get {
                return ResourceManager.GetString("lblPmPaymentPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先担当者.
        /// </summary>
        public static string lblPmPicName {
            get {
                return ResourceManager.GetString("lblPmPicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払調整額.
        /// </summary>
        public static string lblPmReceivedAdjustment {
            get {
                return ResourceManager.GetString("lblPmReceivedAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払合計額.
        /// </summary>
        public static string lblPmTotalPaymentAmount {
            get {
                return ResourceManager.GetString("lblPmTotalPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払税込合計額.
        /// </summary>
        public static string lblPmTotalPaymentAmountIncludeTax {
            get {
                return ResourceManager.GetString("lblPmTotalPaymentAmountIncludeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単価支払額.
        /// </summary>
        public static string lblPmUnitPrice {
            get {
                return ResourceManager.GetString("lblPmUnitPrice", resourceCulture);
            }
        }
    }
}
