//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssueOrderForPayment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueOrderForPayment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.IssueOrderForPayment", typeof(IssueOrderForPayment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全チェック.
        /// </summary>
        public static string btnCheckAll {
            get {
                return ResourceManager.GetString("btnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注文書発行.
        /// </summary>
        public static string btnIssueOrders {
            get {
                return ResourceManager.GetString("btnIssueOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全チェック解除.
        /// </summary>
        public static string btnUncheckAll {
            get {
                return ResourceManager.GetString("btnUncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検収日.
        /// </summary>
        public static string lblAcceptanceDate {
            get {
                return ResourceManager.GetString("lblAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先担当者名.
        /// </summary>
        public static string lblBillingContactName {
            get {
                return ResourceManager.GetString("lblBillingContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string lblBillingDestination {
            get {
                return ResourceManager.GetString("lblBillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先担当.
        /// </summary>
        public static string lblBillingDestinationPIC {
            get {
                return ResourceManager.GetString("lblBillingDestinationPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先担当部署.
        /// </summary>
        public static string lblBillingGroupName {
            get {
                return ResourceManager.GetString("lblBillingGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間.
        /// </summary>
        public static string lblContractDuration {
            get {
                return ResourceManager.GetString("lblContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間（終了）.
        /// </summary>
        public static string lblContractDurationEnd {
            get {
                return ResourceManager.GetString("lblContractDurationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間（開始）.
        /// </summary>
        public static string lblContractDurationStart {
            get {
                return ResourceManager.GetString("lblContractDurationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約終了日.
        /// </summary>
        public static string lblContractEndDate {
            get {
                return ResourceManager.GetString("lblContractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約開始日.
        /// </summary>
        public static string lblContractStartDate {
            get {
                return ResourceManager.GetString("lblContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約状況.
        /// </summary>
        public static string lblContractState {
            get {
                return ResourceManager.GetString("lblContractState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約種別.
        /// </summary>
        public static string lblContractType {
            get {
                return ResourceManager.GetString("lblContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品日.
        /// </summary>
        public static string lblDeliveryDate {
            get {
                return ResourceManager.GetString("lblDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間.
        /// </summary>
        public static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先用注文書発行.
        /// </summary>
        public static string lblIssueOrderForPayment {
            get {
                return ResourceManager.GetString("lblIssueOrderForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要注意.
        /// </summary>
        public static string lblNeedCaution {
            get {
                return ResourceManager.GetString("lblNeedCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受注金額.
        /// </summary>
        public static string lblOrderAcceptanceAmount {
            get {
                return ResourceManager.GetString("lblOrderAcceptanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払金額.
        /// </summary>
        public static string lblPaymentAmount {
            get {
                return ResourceManager.GetString("lblPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先担当者名.
        /// </summary>
        public static string lblPaymentContactName {
            get {
                return ResourceManager.GetString("lblPaymentContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先.
        /// </summary>
        public static string lblPaymentDestination {
            get {
                return ResourceManager.GetString("lblPaymentDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先担当.
        /// </summary>
        public static string lblPaymentDestinationPIC {
            get {
                return ResourceManager.GetString("lblPaymentDestinationPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先担当部署.
        /// </summary>
        public static string lblPaymentGroupName {
            get {
                return ResourceManager.GetString("lblPaymentGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string lblProjectName {
            get {
                return ResourceManager.GetString("lblProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件参画日.
        /// </summary>
        public static string lblProjectParticipationDate {
            get {
                return ResourceManager.GetString("lblProjectParticipationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業者／品名.
        /// </summary>
        public static string lblWorkerProductName {
            get {
                return ResourceManager.GetString("lblWorkerProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 締.
        /// </summary>
        public static string txtClosing {
            get {
                return ResourceManager.GetString("txtClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先注文書.
        /// </summary>
        public static string txtIssueOrderforPayment {
            get {
                return ResourceManager.GetString("txtIssueOrderforPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 払.
        /// </summary>
        public static string txtPayment {
            get {
                return ResourceManager.GetString("txtPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税抜.
        /// </summary>
        public static string txtTaxExcluded {
            get {
                return ResourceManager.GetString("txtTaxExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税込.
        /// </summary>
        public static string txtTaxIncluded {
            get {
                return ResourceManager.GetString("txtTaxIncluded", resourceCulture);
            }
        }
    }
}
