//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your input content is not correct or account is not registered.
        /// </summary>
        public static string AccountFailed {
            get {
                return ResourceManager.GetString("AccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザアカウントはロックされました。管理者に連絡をしてください。.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規に追加した行.
        /// </summary>
        public static string AddLine {
            get {
                return ResourceManager.GetString("AddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容で登録します。\nよろしいですか？.
        /// </summary>
        public static string AuthenticateTimeout {
            get {
                return ResourceManager.GetString("AuthenticateTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求一覧画面に遷移します。よろしいですか？.
        /// </summary>
        public static string BackBillingConfirm {
            get {
                return ResourceManager.GetString("BackBillingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約一覧画面に遷移します。よろしいですか？.
        /// </summary>
        public static string BackContractConfirm {
            get {
                return ResourceManager.GetString("BackContractConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積一覧画面に遷移します。よろしいですか？.
        /// </summary>
        public static string BackEstimateConfirm {
            get {
                return ResourceManager.GetString("BackEstimateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積情報一覧（契約）画面に遷移します。よろしいですか？.
        /// </summary>
        public static string BackEstimateContractConfirm {
            get {
                return ResourceManager.GetString("BackEstimateContractConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払一覧画面に遷移します。よろしいですか？.
        /// </summary>
        public static string BackPaymentListConfirm {
            get {
                return ResourceManager.GetString("BackPaymentListConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書を発行していないので、注文書を発行することはできません。.
        /// </summary>
        public static string CanNotCreateOrderFile {
            get {
                return ResourceManager.GetString("CanNotCreateOrderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの変更に成功しました。.
        /// </summary>
        public static string ChangePassSuccess {
            get {
                return ResourceManager.GetString("ChangePassSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力内容を消去しますか？.
        /// </summary>
        public static string ClearEstimateConfirm {
            get {
                return ResourceManager.GetString("ClearEstimateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;支払日は締日より後の日を選択してください。&quot;.
        /// </summary>
        public static string ClosingDayBiggerthanPaymentDay {
            get {
                return ResourceManager.GetString("ClosingDayBiggerthanPaymentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容でカテゴリを複製します。よろしいですか？.
        /// </summary>
        public static string ComfirmDuplicateCategory {
            get {
                return ResourceManager.GetString("ComfirmDuplicateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力した内容が失われます。よろしいですか？.
        /// </summary>
        public static string ConfirmBack {
            get {
                return ResourceManager.GetString("ConfirmBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力した内容が失われます。よろしいですか？.
        /// </summary>
        public static string ConfirmChangeProduct {
            get {
                return ResourceManager.GetString("ConfirmChangeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力した内容が失われます。よろしいですか？.
        /// </summary>
        public static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力した内容が失われます。よろしいですか？.
        /// </summary>
        public static string ConfirmClosePopup {
            get {
                return ResourceManager.GetString("ConfirmClosePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積閲覧画面を閉じます。よろしいですか？.
        /// </summary>
        public static string ConfirmCloseViewEstimate {
            get {
                return ResourceManager.GetString("ConfirmCloseViewEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書を作成します。\nよろしいですか？.
        /// </summary>
        public static string ConfirmCreateBilling {
            get {
                return ResourceManager.GetString("ConfirmCreateBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添付ファイルを削除しますか？.
        /// </summary>
        public static string ConfirmDeleteAttachedFile {
            get {
                return ResourceManager.GetString("ConfirmDeleteAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to の請求準備情報を削除します。よろしいですか？.
        /// </summary>
        public static string ConfirmDeleteBilling {
            get {
                return ResourceManager.GetString("ConfirmDeleteBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約の削除を行います。宜しいですか？.
        /// </summary>
        public static string ConfirmDeleteContract {
            get {
                return ResourceManager.GetString("ConfirmDeleteContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to の見積情報を削除します。よろしいですか？.
        /// </summary>
        public static string ConfirmDeleteEstimate {
            get {
                return ResourceManager.GetString("ConfirmDeleteEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金情報を登録してもよろしいですか？.
        /// </summary>
        public static string ConfirmDepositPayment {
            get {
                return ResourceManager.GetString("ConfirmDepositPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書を発行します。\nよろしいですか？.
        /// </summary>
        public static string ConfirmExportEstimate {
            get {
                return ResourceManager.GetString("ConfirmExportEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注文書を発行します。\nよろしいですか？.
        /// </summary>
        public static string ConfirmExportOrders {
            get {
                return ResourceManager.GetString("ConfirmExportOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約を終了しても、よろしいでしょうか。.
        /// </summary>
        public static string ConfirmFinishContract {
            get {
                return ResourceManager.GetString("ConfirmFinishContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この見積書を発行しますか？.
        /// </summary>
        public static string ConfirmIssueEstimate {
            get {
                return ResourceManager.GetString("ConfirmIssueEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この注文書を発行しますか？.
        /// </summary>
        public static string ConfirmIssueOrder {
            get {
                return ResourceManager.GetString("ConfirmIssueOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先用注文書を発行します。\nよろしいですか？.
        /// </summary>
        public static string ConfirmIssueOrderforPayment {
            get {
                return ResourceManager.GetString("ConfirmIssueOrderforPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書追加フォーマットの情報を更新します。よろしいですか？.
        /// </summary>
        public static string ConfirmRegistDebitNote {
            get {
                return ResourceManager.GetString("ConfirmRegistDebitNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 派遣契約諸表登録の情報を更新します。よろしいですか？.
        /// </summary>
        public static string ConfirmRegistDispatchContractOverhead {
            get {
                return ResourceManager.GetString("ConfirmRegistDispatchContractOverhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容で登録します。よろしいですか？.
        /// </summary>
        public static string ConfirmRegister {
            get {
                return ResourceManager.GetString("ConfirmRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求情報を更新します。よろしいですか？.
        /// </summary>
        public static string ConfirmRegisterBilling {
            get {
                return ResourceManager.GetString("ConfirmRegisterBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容で登録します。 よろしいですか？.
        /// </summary>
        public static string ConfirmRegisterCustomer {
            get {
                return ResourceManager.GetString("ConfirmRegisterCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容で登録します。\nよろしいですか？.
        /// </summary>
        public static string ConfirmRegisterEstimate {
            get {
                return ResourceManager.GetString("ConfirmRegisterEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容で登録します。 よろしいですか？.
        /// </summary>
        public static string ConfirmRegisterPartnerAddress {
            get {
                return ResourceManager.GetString("ConfirmRegisterPartnerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容で登録します。 よろしいですか？.
        /// </summary>
        public static string ConfirmRegisterPartnerStaff {
            get {
                return ResourceManager.GetString("ConfirmRegisterPartnerStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赤伝を登録してもよろしいですか？.
        /// </summary>
        public static string ConfirmRegisterRedInvoice {
            get {
                return ResourceManager.GetString("ConfirmRegisterRedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先派遣契約諸表の情報を更新します。よろしいですか？.
        /// </summary>
        public static string ConfirmRegistPaymentDispatchContractOverhead {
            get {
                return ResourceManager.GetString("ConfirmRegistPaymentDispatchContractOverhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この見積書の送付日を登録します。\nよろしいですか？.
        /// </summary>
        public static string ConfirmSendEstimate {
            get {
                return ResourceManager.GetString("ConfirmSendEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dou want to {0} this item for lunch。\Is that right？.
        /// </summary>
        public static string ConfirmSubmitData {
            get {
                return ResourceManager.GetString("ConfirmSubmitData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容で更新します。よろしいですか？.
        /// </summary>
        public static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約の削除に失敗しました。.
        /// </summary>
        public static string ContractDeleteFail {
            get {
                return ResourceManager.GetString("ContractDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約を削除しました。.
        /// </summary>
        public static string ContractDeleteSuccess {
            get {
                return ResourceManager.GetString("ContractDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書を作成しました。.
        /// </summary>
        public static string CreatedInvoice {
            get {
                return ResourceManager.GetString("CreatedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの作成に失敗しました。.
        /// </summary>
        public static string CreateFileFailed {
            get {
                return ResourceManager.GetString("CreateFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注文書を出力しました。.
        /// </summary>
        public static string CreateOrderFileSuccess {
            get {
                return ResourceManager.GetString("CreateOrderFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更されたレコードが存在しません。.
        /// </summary>
        public static string DoesNotExistChangedData {
            get {
                return ResourceManager.GetString("DoesNotExistChangedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力された勘定科目コードは既に存在しています。.
        /// </summary>
        public static string DuplicateAccountCd {
            get {
                return ResourceManager.GetString("DuplicateAccountCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力された取引先名は既に存在しています。.
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間終了日は期間開始日より未来の日付を入力して下さい。.
        /// </summary>
        public static string EndDateLessStartDateWarning {
            get {
                return ResourceManager.GetString("EndDateLessStartDateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以降を指定してください。.
        /// </summary>
        public static string ErrCompareTwoDate {
            get {
                return ResourceManager.GetString("ErrCompareTwoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間単位は60分以内で入力してください..
        /// </summary>
        public static string ErrRangeUnitTime {
            get {
                return ResourceManager.GetString("ErrRangeUnitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力された年月は既に存在しています。.
        /// </summary>
        public static string ErrTargetYmDuplicate {
            get {
                return ResourceManager.GetString("ErrTargetYmDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続の有効時間が切れました。再度ログインしなおしてください。.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展開フラグの取得に失敗しました。.
        /// </summary>
        public static string FailedExpandFlg {
            get {
                return ResourceManager.GetString("FailedExpandFlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製品の取得に失敗しました。.
        /// </summary>
        public static string FailedProduct {
            get {
                return ResourceManager.GetString("FailedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積書送付フラグの更新に失敗しました。.
        /// </summary>
        public static string FailedSendFlag {
            get {
                return ResourceManager.GetString("FailedSendFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サブ契約種別の取得に失敗しました。.
        /// </summary>
        public static string FailedSubContract {
            get {
                return ResourceManager.GetString("FailedSubContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主担当者名を取得できません。.
        /// </summary>
        public static string GetPicFailed {
            get {
                return ResourceManager.GetString("GetPicFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の入力形式に誤りがあります。.
        /// </summary>
        public static string IncorrectFormat {
            get {
                return ResourceManager.GetString("IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力に誤りがあります。修正してください。.
        /// </summary>
        public static string InputIncorrect {
            get {
                return ResourceManager.GetString("InputIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の入力が長すぎます。.
        /// </summary>
        public static string InputLengthErr {
            get {
                return ResourceManager.GetString("InputLengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の入力が大きすぎます。.
        /// </summary>
        public static string InputNumErr {
            get {
                return ResourceManager.GetString("InputNumErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約月数がおまとめ請求の月数で割り切れません。.
        /// </summary>
        public static string Invalid_collect_contract_month {
            get {
                return ResourceManager.GetString("Invalid_collect_contract_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の指定が正しくありません。.
        /// </summary>
        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の入力が長すぎます。.
        /// </summary>
        public static string MaxByte {
            get {
                return ResourceManager.GetString("MaxByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}文字以内で入力してください..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号に該当する住所情報が見つかりません。.
        /// </summary>
        public static string NoAddressWarning {
            get {
                return ResourceManager.GetString("NoAddressWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「契約種別」と「契約種別分類」を選択してください。.
        /// </summary>
        public static string NoSelectContractType {
            get {
                return ResourceManager.GetString("NoSelectContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「契約種別」を選択してください。.
        /// </summary>
        public static string NoSelectContractTypeClass {
            get {
                return ResourceManager.GetString("NoSelectContractTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求情報を選択してください。.
        /// </summary>
        public static string NotSelectedBillingTarget {
            get {
                return ResourceManager.GetString("NotSelectedBillingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを変更することができません。.
        /// </summary>
        public static string PasswordChangeFailed {
            get {
                return ResourceManager.GetString("PasswordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードが{0}ヶ月以上変更されていません。\nパスワードを変更してください。い。.
        /// </summary>
        public static string PasswordExpired {
            get {
                return ResourceManager.GetString("PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力されたパスワードは使用できません。.
        /// </summary>
        public static string PasswordInvalidCharacter {
            get {
                return ResourceManager.GetString("PasswordInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの長さが正しくありません。.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更前と同一のパスワードは設定できません。.
        /// </summary>
        public static string PasswordNotChanged {
            get {
                return ResourceManager.GetString("PasswordNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新パスワード と 新パスワード（確認）が一致していません。.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの有効期限が切れました。\nパスワードを変更してください。.
        /// </summary>
        public static string PasswordOnExpired {
            get {
                return ResourceManager.GetString("PasswordOnExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの複雑度が不足しています。.
        /// </summary>
        public static string PasswordStrength {
            get {
                return ResourceManager.GetString("PasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトルは必須項目です。.
        /// </summary>
        public static string PostInformationTitleRequired {
            get {
                return ResourceManager.GetString("PostInformationTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}と{2}文字以内で入力してください..
        /// </summary>
        public static string RangeValue {
            get {
                return ResourceManager.GetString("RangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の登録に失敗しました。.
        /// </summary>
        public static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を{1}しました。.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力されたパスワード（確認）は使用できません。.
        /// </summary>
        public static string RePasswordInvalidCharacter {
            get {
                return ResourceManager.GetString("RePasswordInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新パスワード（確認）の長さが正しくありません。.
        /// </summary>
        public static string RePasswordLength {
            get {
                return ResourceManager.GetString("RePasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所を上書きします。よろしいですか？.
        /// </summary>
        public static string ReplaceAddressWarning {
            get {
                return ResourceManager.GetString("ReplaceAddressWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は必須項目です。.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に入金済みのため、契約を更新することは出来ません。.
        /// </summary>
        public static string UnableUpdateContract {
            get {
                return ResourceManager.GetString("UnableUpdateContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求情報を更新することができませんでした。.
        /// </summary>
        public static string UpdateBillingFailed {
            get {
                return ResourceManager.GetString("UpdateBillingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求情報を更新しました。.
        /// </summary>
        public static string UpdateBillingSuccess {
            get {
                return ResourceManager.GetString("UpdateBillingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約情報を更新しました。.
        /// </summary>
        public static string UpdateContractSuccess {
            get {
                return ResourceManager.GetString("UpdateContractSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新に失敗しました。.
        /// </summary>
        public static string UpdateDebitNoteFailed {
            get {
                return ResourceManager.GetString("UpdateDebitNoteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新が成功しました。.
        /// </summary>
        public static string UpdateDebitNoteSuccess {
            get {
                return ResourceManager.GetString("UpdateDebitNoteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見積情報を更新しました。.
        /// </summary>
        public static string UpdateEstimateSuccess {
            get {
                return ResourceManager.GetString("UpdateEstimateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新に失敗しました。.
        /// </summary>
        public static string UpdateFailDisptachContractOverhead {
            get {
                return ResourceManager.GetString("UpdateFailDisptachContractOverhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金消込情報を更新することができませんでした。.
        /// </summary>
        public static string UpdatePaymentClearFailed {
            get {
                return ResourceManager.GetString("UpdatePaymentClearFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金消込情報を更新しました。.
        /// </summary>
        public static string UpdatePaymentClearSuccess {
            get {
                return ResourceManager.GetString("UpdatePaymentClearSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書情報を更新しました。.
        /// </summary>
        public static string UpdatePaymentInfor {
            get {
                return ResourceManager.GetString("UpdatePaymentInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赤伝を更新することができませんでした。.
        /// </summary>
        public static string UpdateRedInvoiceFailed {
            get {
                return ResourceManager.GetString("UpdateRedInvoiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赤伝を更新しました。.
        /// </summary>
        public static string UpdateRedInvoiceSuccess {
            get {
                return ResourceManager.GetString("UpdateRedInvoiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新しました。.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新が成功しました。.
        /// </summary>
        public static string UpdateSuccessDispatchContractOverhead {
            get {
                return ResourceManager.GetString("UpdateSuccessDispatchContractOverhead", resourceCulture);
            }
        }
    }
}
