//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mst_PlanMainList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mst_PlanMainList() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.Mst_PlanMainList", typeof(Mst_PlanMainList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   削除フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DEL_FLG {
            get {
                return ResourceManager.GetString("DEL_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DISABLE_FLG {
            get {
                return ResourceManager.GetString("DISABLE_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INS_DATE {
            get {
                return ResourceManager.GetString("INS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成者ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INS_USER_ID {
            get {
                return ResourceManager.GetString("INS_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント数上限値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOGIN_ACCOUNT_UPPER {
            get {
                return ResourceManager.GetString("LOGIN_ACCOUNT_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月間請求データ数上限値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MONTHLY_BILL_DAtA_UPPER {
            get {
                return ResourceManager.GetString("MONTHLY_BILL_DAtA_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PLAN_BASE_PRICE {
            get {
                return ResourceManager.GetString("PLAN_BASE_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プランコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PLAN_CD {
            get {
                return ResourceManager.GetString("PLAN_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラン名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PLAN_NAME {
            get {
                return ResourceManager.GetString("PLAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラン通し番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PLAN_SEQ_NO {
            get {
                return ResourceManager.GetString("PLAN_SEQ_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UPD_DATE {
            get {
                return ResourceManager.GetString("UPD_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新プログラムID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UPD_PROG_ID {
            get {
                return ResourceManager.GetString("UPD_PROG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新者ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UPD_USER_ID {
            get {
                return ResourceManager.GetString("UPD_USER_ID", resourceCulture);
            }
        }
    }
}
