//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NumberTempName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberTempName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.NumberTempName", typeof(NumberTempName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to さ.
        /// </summary>
        public static string _01 {
            get {
                return ResourceManager.GetString("01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to す.
        /// </summary>
        public static string _02 {
            get {
                return ResourceManager.GetString("02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to せ.
        /// </summary>
        public static string _03 {
            get {
                return ResourceManager.GetString("03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to そ.
        /// </summary>
        public static string _04 {
            get {
                return ResourceManager.GetString("04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to た.
        /// </summary>
        public static string _05 {
            get {
                return ResourceManager.GetString("05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ち.
        /// </summary>
        public static string _06 {
            get {
                return ResourceManager.GetString("06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to つ.
        /// </summary>
        public static string _07 {
            get {
                return ResourceManager.GetString("07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to て.
        /// </summary>
        public static string _08 {
            get {
                return ResourceManager.GetString("08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to と.
        /// </summary>
        public static string _09 {
            get {
                return ResourceManager.GetString("09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to な.
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to に.
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぬ.
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ね.
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to の.
        /// </summary>
        public static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to は.
        /// </summary>
        public static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひ.
        /// </summary>
        public static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふ.
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to へ.
        /// </summary>
        public static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ほ.
        /// </summary>
        public static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ま.
        /// </summary>
        public static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to み.
        /// </summary>
        public static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to む.
        /// </summary>
        public static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to め.
        /// </summary>
        public static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to も.
        /// </summary>
        public static string _24 {
            get {
                return ResourceManager.GetString("24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to や.
        /// </summary>
        public static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゆ.
        /// </summary>
        public static string _26 {
            get {
                return ResourceManager.GetString("26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ら.
        /// </summary>
        public static string _27 {
            get {
                return ResourceManager.GetString("27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to り.
        /// </summary>
        public static string _28 {
            get {
                return ResourceManager.GetString("28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to る.
        /// </summary>
        public static string _29 {
            get {
                return ResourceManager.GetString("29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ろ.
        /// </summary>
        public static string _30 {
            get {
                return ResourceManager.GetString("30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あ.
        /// </summary>
        public static string _31 {
            get {
                return ResourceManager.GetString("31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to い.
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to う.
        /// </summary>
        public static string _33 {
            get {
                return ResourceManager.GetString("33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to え.
        /// </summary>
        public static string _34 {
            get {
                return ResourceManager.GetString("34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to か.
        /// </summary>
        public static string _35 {
            get {
                return ResourceManager.GetString("35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to き.
        /// </summary>
        public static string _36 {
            get {
                return ResourceManager.GetString("36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to く.
        /// </summary>
        public static string _37 {
            get {
                return ResourceManager.GetString("37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to け.
        /// </summary>
        public static string _38 {
            get {
                return ResourceManager.GetString("38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to こ.
        /// </summary>
        public static string _39 {
            get {
                return ResourceManager.GetString("39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to を.
        /// </summary>
        public static string _40 {
            get {
                return ResourceManager.GetString("40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to わ.
        /// </summary>
        public static string _41 {
            get {
                return ResourceManager.GetString("41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to れ.
        /// </summary>
        public static string _42 {
            get {
                return ResourceManager.GetString("42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string _43 {
            get {
                return ResourceManager.GetString("43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string _44 {
            get {
                return ResourceManager.GetString("44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string _45 {
            get {
                return ResourceManager.GetString("45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string _46 {
            get {
                return ResourceManager.GetString("46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string _47 {
            get {
                return ResourceManager.GetString("47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string _48 {
            get {
                return ResourceManager.GetString("48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to よ.
        /// </summary>
        public static string _49 {
            get {
                return ResourceManager.GetString("49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
    }
}
