//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PartnerStaffRegister {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerStaffRegister() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.PartnerStaffRegister", typeof(PartnerStaffRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一覧にない住所を入力.
        /// </summary>
        public static string btnInputAddress {
            get {
                return ResourceManager.GetString("btnInputAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所１.
        /// </summary>
        public static string lblAddress1 {
            get {
                return ResourceManager.GetString("lblAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所２.
        /// </summary>
        public static string lblAddress2 {
            get {
                return ResourceManager.GetString("lblAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求担当者.
        /// </summary>
        public static string lblBillingPIC {
            get {
                return ResourceManager.GetString("lblBillingPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成者.
        /// </summary>
        public static string lblCreatedBy {
            get {
                return ResourceManager.GetString("lblCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成日.
        /// </summary>
        public static string lblCreatedDate {
            get {
                return ResourceManager.GetString("lblCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引担当者.
        /// </summary>
        public static string lblCustomerPIC {
            get {
                return ResourceManager.GetString("lblCustomerPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内線.
        /// </summary>
        public static string lblExt {
            get {
                return ResourceManager.GetString("lblExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX番号.
        /// </summary>
        public static string lblFaxNo {
            get {
                return ResourceManager.GetString("lblFaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部署名.
        /// </summary>
        public static string lblGroupName {
            get {
                return ResourceManager.GetString("lblGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者情報.
        /// </summary>
        public static string lblHeader {
            get {
                return ResourceManager.GetString("lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレス.
        /// </summary>
        public static string lblMailAddress {
            get {
                return ResourceManager.GetString("lblMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先表示名.
        /// </summary>
        public static string lblPartnerDisplayName {
            get {
                return ResourceManager.GetString("lblPartnerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先正式名.
        /// </summary>
        public static string lblPartnerOfficalName {
            get {
                return ResourceManager.GetString("lblPartnerOfficalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 役職.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号.
        /// </summary>
        public static string lblPostalCode {
            get {
                return ResourceManager.GetString("lblPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号内線.
        /// </summary>
        public static string lblStaffFax {
            get {
                return ResourceManager.GetString("lblStaffFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者名.
        /// </summary>
        public static string lblStaffName {
            get {
                return ResourceManager.GetString("lblStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者名（カナ）.
        /// </summary>
        public static string lblStaffNameKana {
            get {
                return ResourceManager.GetString("lblStaffNameKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号内線.
        /// </summary>
        public static string lblStaffTel {
            get {
                return ResourceManager.GetString("lblStaffTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号.
        /// </summary>
        public static string lblTelNo {
            get {
                return ResourceManager.GetString("lblTelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新者.
        /// </summary>
        public static string lblUpdatedBy {
            get {
                return ResourceManager.GetString("lblUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日.
        /// </summary>
        public static string lblUpdatedDate {
            get {
                return ResourceManager.GetString("lblUpdatedDate", resourceCulture);
            }
        }
    }
}
