//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentClear {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentClear() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.PaymentClear", typeof(PaymentClear).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差額を支払手数料にして確定.
        /// </summary>
        public static string btnConfirmDiffFee {
            get {
                return ResourceManager.GetString("btnConfirmDiffFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赤伝作成.
        /// </summary>
        public static string btnCreateRedInvoice {
            get {
                return ResourceManager.GetString("btnCreateRedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差額はそのままで確定.
        /// </summary>
        public static string btnKeepFee {
            get {
                return ResourceManager.GetString("btnKeepFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振分.
        /// </summary>
        public static string btnSplit {
            get {
                return ResourceManager.GetString("btnSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to は差額以下の金額を入力してください。.
        /// </summary>
        public static string errGreaterThanBalance {
            get {
                return ResourceManager.GetString("errGreaterThanBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to は9桁以内で入力してください。.
        /// </summary>
        public static string errMaxValueRange {
            get {
                return ResourceManager.GetString("errMaxValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今回入金総額を入力してください。.
        /// </summary>
        public static string errMissingCurrentDepositAmount {
            get {
                return ResourceManager.GetString("errMissingCurrentDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to は正の整数で入力してください。.
        /// </summary>
        public static string errNotPositiveInteger {
            get {
                return ResourceManager.GetString("errNotPositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今回入金総額が正しく振り分けられていません。.
        /// </summary>
        public static string errPaymentWrongAllocation {
            get {
                return ResourceManager.GetString("errPaymentWrongAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勘定科目.
        /// </summary>
        public static string lblAccountClass {
            get {
                return ResourceManager.GetString("lblAccountClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補助科目.
        /// </summary>
        public static string lblAuxiliaryClass {
            get {
                return ResourceManager.GetString("lblAuxiliaryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string lblBillingDestination {
            get {
                return ResourceManager.GetString("lblBillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今回入金総額.
        /// </summary>
        public static string lblCurrentTotalAmount {
            get {
                return ResourceManager.GetString("lblCurrentTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差額.
        /// </summary>
        public static string lblDifference {
            get {
                return ResourceManager.GetString("lblDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差額.
        /// </summary>
        public static string lblDifferenceMoney {
            get {
                return ResourceManager.GetString("lblDifferenceMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金日.
        /// </summary>
        public static string lblReceivedMoneyDate {
            get {
                return ResourceManager.GetString("lblReceivedMoneyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取り消す入金額.
        /// </summary>
        public static string lblReceivedMoneyStatusCancel {
            get {
                return ResourceManager.GetString("lblReceivedMoneyStatusCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求月.
        /// </summary>
        public static string TH_BillingMonth {
            get {
                return ResourceManager.GetString("TH_BillingMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求番号.
        /// </summary>
        public static string TH_BillingNumber {
            get {
                return ResourceManager.GetString("TH_BillingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差額.
        /// </summary>
        public static string TH_DifferenceMoney {
            get {
                return ResourceManager.GetString("TH_DifferenceMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金後差額.
        /// </summary>
        public static string TH_DiffereneMoneyAfterReceive {
            get {
                return ResourceManager.GetString("TH_DiffereneMoneyAfterReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既入金額.
        /// </summary>
        public static string TH_ExistingPaymentAmount {
            get {
                return ResourceManager.GetString("TH_ExistingPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （手数料）.
        /// </summary>
        public static string TH_Fee {
            get {
                return ResourceManager.GetString("TH_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金額.
        /// </summary>
        public static string TH_ReceivedAmount {
            get {
                return ResourceManager.GetString("TH_ReceivedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取り消す入金額.
        /// </summary>
        public static string TH_ReceivedAmountAfterCancel {
            get {
                return ResourceManager.GetString("TH_ReceivedAmountAfterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計入金額.
        /// </summary>
        public static string TH_ReceivedAmoutTotal {
            get {
                return ResourceManager.GetString("TH_ReceivedAmoutTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金予定日.
        /// </summary>
        public static string TH_ReceivedMoneyPayPlan {
            get {
                return ResourceManager.GetString("TH_ReceivedMoneyPayPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金状況.
        /// </summary>
        public static string TH_ReceivedMoneyStatusCancel {
            get {
                return ResourceManager.GetString("TH_ReceivedMoneyStatusCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金後状況.
        /// </summary>
        public static string TH_StateAfterReceiveMoney {
            get {
                return ResourceManager.GetString("TH_StateAfterReceiveMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書検索用タグ.
        /// </summary>
        public static string TH_TagSearchDebitNote {
            get {
                return ResourceManager.GetString("TH_TagSearchDebitNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税込請求額.
        /// </summary>
        public static string TH_TaxIncludedBillingAmount {
            get {
                return ResourceManager.GetString("TH_TaxIncludedBillingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金消込.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未入金.
        /// </summary>
        public static string txtNotPaid {
            get {
                return ResourceManager.GetString("txtNotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金済.
        /// </summary>
        public static string txtPaid {
            get {
                return ResourceManager.GetString("txtPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一部未入金.
        /// </summary>
        public static string txtPartOfPaymentNotReceived {
            get {
                return ResourceManager.GetString("txtPartOfPaymentNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 円.
        /// </summary>
        public static string txtYen {
            get {
                return ResourceManager.GetString("txtYen", resourceCulture);
            }
        }
    }
}
