//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentNotPaymentSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentNotPaymentSearch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.PaymentNotPaymentSearch", typeof(PaymentNotPaymentSearch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金消込に進む.
        /// </summary>
        public static string btnProceedToClearPayment {
            get {
                return ResourceManager.GetString("btnProceedToClearPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消込.
        /// </summary>
        public static string cbClear {
            get {
                return ResourceManager.GetString("cbClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勘定科目.
        /// </summary>
        public static string lblAccountClass {
            get {
                return ResourceManager.GetString("lblAccountClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手数料.
        /// </summary>
        public static string lblAdjustmentAmount {
            get {
                return ResourceManager.GetString("lblAdjustmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて.
        /// </summary>
        public static string lblAllType {
            get {
                return ResourceManager.GetString("lblAllType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補助科目.
        /// </summary>
        public static string lblAuxiliaryClass {
            get {
                return ResourceManager.GetString("lblAuxiliaryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差額.
        /// </summary>
        public static string lblBalanceAmount {
            get {
                return ResourceManager.GetString("lblBalanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税込請求額.
        /// </summary>
        public static string lblBillingAmountOnTax {
            get {
                return ResourceManager.GetString("lblBillingAmountOnTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書検索用タグ.
        /// </summary>
        public static string lblBillingDspTag {
            get {
                return ResourceManager.GetString("lblBillingDspTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求月.
        /// </summary>
        public static string lblBillingMonth {
            get {
                return ResourceManager.GetString("lblBillingMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求番号.
        /// </summary>
        public static string lblBillingNo {
            get {
                return ResourceManager.GetString("lblBillingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string lblBpDspName {
            get {
                return ResourceManager.GetString("lblBpDspName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先カナ.
        /// </summary>
        public static string lblBPDspNameKana {
            get {
                return ResourceManager.GetString("lblBPDspNameKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金日.
        /// </summary>
        public static string lblDepositDate {
            get {
                return ResourceManager.GetString("lblDepositDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金予定日.
        /// </summary>
        public static string lblDepositPlanDate {
            get {
                return ResourceManager.GetString("lblDepositPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金状況.
        /// </summary>
        public static string lblDepositStateType {
            get {
                return ResourceManager.GetString("lblDepositStateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月分.
        /// </summary>
        public static string lblMonthly {
            get {
                return ResourceManager.GetString("lblMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直近入金日.
        /// </summary>
        public static string lblMostRecentPaymentDate {
            get {
                return ResourceManager.GetString("lblMostRecentPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未入金／一部未入金.
        /// </summary>
        public static string lblNotRecievedPart {
            get {
                return ResourceManager.GetString("lblNotRecievedPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金済額.
        /// </summary>
        public static string lblReceiveAmount {
            get {
                return ResourceManager.GetString("lblReceiveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金済.
        /// </summary>
        public static string lblReceived {
            get {
                return ResourceManager.GetString("lblReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※必須.
        /// </summary>
        public static string lblRequire {
            get {
                return ResourceManager.GetString("lblRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金消込設定.
        /// </summary>
        public static string lblSettingClearReceivedMoney {
            get {
                return ResourceManager.GetString("lblSettingClearReceivedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日.
        /// </summary>
        public static string lblToday {
            get {
                return ResourceManager.GetString("lblToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェックしたレコードの差額合計.
        /// </summary>
        public static string lblTotalBalanceAmount {
            get {
                return ResourceManager.GetString("lblTotalBalanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金・未入金検索.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
