//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentHistory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentHistory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.PaymentHistory", typeof(PaymentHistory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日.
        /// </summary>
        public static string btnToday {
            get {
                return ResourceManager.GetString("btnToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勘定科目.
        /// </summary>
        public static string lblAccountClass {
            get {
                return ResourceManager.GetString("lblAccountClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補助科目.
        /// </summary>
        public static string lblAuxiliaryClass {
            get {
                return ResourceManager.GetString("lblAuxiliaryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string lblBillingDestination {
            get {
                return ResourceManager.GetString("lblBillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先カナ.
        /// </summary>
        public static string lblBillingDestinationKana {
            get {
                return ResourceManager.GetString("lblBillingDestinationKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金日.
        /// </summary>
        public static string lblDepositeDate {
            get {
                return ResourceManager.GetString("lblDepositeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勘定科目.
        /// </summary>
        public static string TH_AccountClass {
            get {
                return ResourceManager.GetString("TH_AccountClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補助科目.
        /// </summary>
        public static string TH_AuxiliaryClass {
            get {
                return ResourceManager.GetString("TH_AuxiliaryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先.
        /// </summary>
        public static string TH_BillingDestination {
            get {
                return ResourceManager.GetString("TH_BillingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赤伝作成.
        /// </summary>
        public static string TH_CreateInvoice {
            get {
                return ResourceManager.GetString("TH_CreateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金額.
        /// </summary>
        public static string TH_DepositeAmount {
            get {
                return ResourceManager.GetString("TH_DepositeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金日.
        /// </summary>
        public static string TH_DepositeDate {
            get {
                return ResourceManager.GetString("TH_DepositeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金履歴検索.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
