//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.PaymentList", typeof(PaymentList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearchDestination {
            get {
                return ResourceManager.GetString("btnSearchDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精算額.
        /// </summary>
        public static string lblAdjustedAmount {
            get {
                return ResourceManager.GetString("lblAdjustedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 調整額.
        /// </summary>
        public static string lblAdjustmentAmount {
            get {
                return ResourceManager.GetString("lblAdjustmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税抜請求額.
        /// </summary>
        public static string lblBillingAmount {
            get {
                return ResourceManager.GetString("lblBillingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税込請求額.
        /// </summary>
        public static string lblBillingAmountTax {
            get {
                return ResourceManager.GetString("lblBillingAmountTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 締日.
        /// </summary>
        public static string lblClosingDay {
            get {
                return ResourceManager.GetString("lblClosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約金額.
        /// </summary>
        public static string lblContractAmount {
            get {
                return ResourceManager.GetString("lblContractAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約期間.
        /// </summary>
        public static string lblContractDuration {
            get {
                return ResourceManager.GetString("lblContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粗利益.
        /// </summary>
        public static string lblGrossProfit {
            get {
                return ResourceManager.GetString("lblGrossProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月分.
        /// </summary>
        public static string lblMonthtly {
            get {
                return ResourceManager.GetString("lblMonthtly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稼働時間.
        /// </summary>
        public static string lblOperateTime {
            get {
                return ResourceManager.GetString("lblOperateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 諸経費.
        /// </summary>
        public static string lblOverheadCost {
            get {
                return ResourceManager.GetString("lblOverheadCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払.
        /// </summary>
        public static string lblPayment {
            get {
                return ResourceManager.GetString("lblPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税抜支払額.
        /// </summary>
        public static string lblPaymentAmount {
            get {
                return ResourceManager.GetString("lblPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税込支払額.
        /// </summary>
        public static string lblPaymentAmountOnTax {
            get {
                return ResourceManager.GetString("lblPaymentAmountOnTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税込支払額.
        /// </summary>
        public static string lblPaymentAmountTax {
            get {
                return ResourceManager.GetString("lblPaymentAmountTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払締日.
        /// </summary>
        public static string lblPaymentClosingDay {
            get {
                return ResourceManager.GetString("lblPaymentClosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先.
        /// </summary>
        public static string lblPaymentDestination {
            get {
                return ResourceManager.GetString("lblPaymentDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払先カナ.
        /// </summary>
        public static string lblPaymentDestinationKana {
            get {
                return ResourceManager.GetString("lblPaymentDestinationKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払月.
        /// </summary>
        public static string lblPaymentMonth {
            get {
                return ResourceManager.GetString("lblPaymentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件名.
        /// </summary>
        public static string lblProjectName {
            get {
                return ResourceManager.GetString("lblProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※必須入力.
        /// </summary>
        public static string lblRequired {
            get {
                return ResourceManager.GetString("lblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 売上.
        /// </summary>
        public static string lblSales {
            get {
                return ResourceManager.GetString("lblSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 集計情報.
        /// </summary>
        public static string lblSummaryInfo {
            get {
                return ResourceManager.GetString("lblSummaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 集計情報（支払）.
        /// </summary>
        public static string lblSummaryInfoPayment {
            get {
                return ResourceManager.GetString("lblSummaryInfoPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交通費.
        /// </summary>
        public static string lblTransportationCost {
            get {
                return ResourceManager.GetString("lblTransportationCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業者／品名.
        /// </summary>
        public static string lblWorker_ProductName {
            get {
                return ResourceManager.GetString("lblWorker_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払一覧.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
