//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScreenIDToCodeValue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreenIDToCodeValue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.ScreenIDToCodeValue", typeof(ScreenIDToCodeValue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 040.
        /// </summary>
        public static string ANNOUNCEMENT {
            get {
                return ResourceManager.GetString("ANNOUNCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 025.
        /// </summary>
        public static string CMB0010 {
            get {
                return ResourceManager.GetString("CMB0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 028.
        /// </summary>
        public static string CMC0010 {
            get {
                return ResourceManager.GetString("CMC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 039.
        /// </summary>
        public static string CMD0010 {
            get {
                return ResourceManager.GetString("CMD0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 036.
        /// </summary>
        public static string CME0010 {
            get {
                return ResourceManager.GetString("CME0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 033.
        /// </summary>
        public static string CMI0010 {
            get {
                return ResourceManager.GetString("CMI0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 029.
        /// </summary>
        public static string CMJ0010 {
            get {
                return ResourceManager.GetString("CMJ0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 030.
        /// </summary>
        public static string CML0010 {
            get {
                return ResourceManager.GetString("CML0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 034.
        /// </summary>
        public static string CMN0010 {
            get {
                return ResourceManager.GetString("CMN0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 035.
        /// </summary>
        public static string CMO0010 {
            get {
                return ResourceManager.GetString("CMO0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 031.
        /// </summary>
        public static string CMS0010 {
            get {
                return ResourceManager.GetString("CMS0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 032.
        /// </summary>
        public static string CMT0010 {
            get {
                return ResourceManager.GetString("CMT0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 022.
        /// </summary>
        public static string COA0010 {
            get {
                return ResourceManager.GetString("COA0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 023.
        /// </summary>
        public static string COB0010 {
            get {
                return ResourceManager.GetString("COB0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024.
        /// </summary>
        public static string COC0010 {
            get {
                return ResourceManager.GetString("COC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 008.
        /// </summary>
        public static string MAA0010 {
            get {
                return ResourceManager.GetString("MAA0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 009.
        /// </summary>
        public static string MAB0010 {
            get {
                return ResourceManager.GetString("MAB0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010.
        /// </summary>
        public static string MAC0010 {
            get {
                return ResourceManager.GetString("MAC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011.
        /// </summary>
        public static string MAD0010 {
            get {
                return ResourceManager.GetString("MAD0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015.
        /// </summary>
        public static string MPA0010 {
            get {
                return ResourceManager.GetString("MPA0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 017.
        /// </summary>
        public static string MPB0010 {
            get {
                return ResourceManager.GetString("MPB0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018.
        /// </summary>
        public static string MPB0015 {
            get {
                return ResourceManager.GetString("MPB0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 019.
        /// </summary>
        public static string MPC0010 {
            get {
                return ResourceManager.GetString("MPC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 020.
        /// </summary>
        public static string MPD0010 {
            get {
                return ResourceManager.GetString("MPD0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 021.
        /// </summary>
        public static string MPE0010 {
            get {
                return ResourceManager.GetString("MPE0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001.
        /// </summary>
        public static string MRA0010 {
            get {
                return ResourceManager.GetString("MRA0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002.
        /// </summary>
        public static string MRB0020 {
            get {
                return ResourceManager.GetString("MRB0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003.
        /// </summary>
        public static string MRC0010 {
            get {
                return ResourceManager.GetString("MRC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004.
        /// </summary>
        public static string MRC0015 {
            get {
                return ResourceManager.GetString("MRC0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005.
        /// </summary>
        public static string MRD0010 {
            get {
                return ResourceManager.GetString("MRD0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006.
        /// </summary>
        public static string TAA0010 {
            get {
                return ResourceManager.GetString("TAA0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007.
        /// </summary>
        public static string TAB0010 {
            get {
                return ResourceManager.GetString("TAB0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 037.
        /// </summary>
        public static string TAC0010 {
            get {
                return ResourceManager.GetString("TAC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 038.
        /// </summary>
        public static string TAD0010 {
            get {
                return ResourceManager.GetString("TAD0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 012.
        /// </summary>
        public static string TCA0020 {
            get {
                return ResourceManager.GetString("TCA0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 041.
        /// </summary>
        public static string TCA0020_DLDATA {
            get {
                return ResourceManager.GetString("TCA0020_DLDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 026.
        /// </summary>
        public static string TMU0010 {
            get {
                return ResourceManager.GetString("TMU0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 026.
        /// </summary>
        public static string TMU0011 {
            get {
                return ResourceManager.GetString("TMU0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 027.
        /// </summary>
        public static string TMW0010 {
            get {
                return ResourceManager.GetString("TMW0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014.
        /// </summary>
        public static string TPA0010 {
            get {
                return ResourceManager.GetString("TPA0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 016.
        /// </summary>
        public static string TPB0010 {
            get {
                return ResourceManager.GetString("TPB0010", resourceCulture);
            }
        }
    }
}
