//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchPartnerStaff {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchPartnerStaff() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.SearchPartnerStaff", typeof(SearchPartnerStaff).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリア.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規担当者入力.
        /// </summary>
        public static string btnRegisterStaff {
            get {
                return ResourceManager.GetString("btnRegisterStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        public static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所識別名.
        /// </summary>
        public static string lblAddrName {
            get {
                return ResourceManager.GetString("lblAddrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先名.
        /// </summary>
        public static string lblCustomerName {
            get {
                return ResourceManager.GetString("lblCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部署名.
        /// </summary>
        public static string lblGroupName {
            get {
                return ResourceManager.GetString("lblGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者名.
        /// </summary>
        public static string lblStaffName {
            get {
                return ResourceManager.GetString("lblStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者名（カナ）.
        /// </summary>
        public static string lblStaffNameKana {
            get {
                return ResourceManager.GetString("lblStaffNameKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者検索.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        public static string linkEdit {
            get {
                return ResourceManager.GetString("linkEdit", resourceCulture);
            }
        }
    }
}
