//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSetup.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SendMailContract {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SendMailContract() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSetup.Constants.Resources.SendMailContract", typeof(SendMailContract).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        public static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信する.
        /// </summary>
        public static string btnSendMail {
            get {
                return ResourceManager.GetString("btnSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC.
        /// </summary>
        public static string lblBCC {
            get {
                return ResourceManager.GetString("lblBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string lblCC {
            get {
                return ResourceManager.GetString("lblCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件変更.
        /// </summary>
        public static string lblChangeCondition {
            get {
                return ResourceManager.GetString("lblChangeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信先.
        /// </summary>
        public static string lblCustomer {
            get {
                return ResourceManager.GetString("lblCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件変更あり.
        /// </summary>
        public static string lblHasConditionChange {
            get {
                return ResourceManager.GetString("lblHasConditionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表題.
        /// </summary>
        public static string lblMailTitle {
            get {
                return ResourceManager.GetString("lblMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重要度.
        /// </summary>
        public static string lblPriorityType {
            get {
                return ResourceManager.GetString("lblPriorityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールを送信しました。.
        /// </summary>
        public static string msgMailSent {
            get {
                return ResourceManager.GetString("msgMailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【期間】.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約確定メール送信.
        /// </summary>
        public static string TitleSendMail {
            get {
                return ResourceManager.GetString("TitleSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［検収日］.
        /// </summary>
        public static string txtAcceptanceDate {
            get {
                return ResourceManager.GetString("txtAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （契約通り）.
        /// </summary>
        public static string txtAccordingToContract {
            get {
                return ResourceManager.GetString("txtAccordingToContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［金額］.
        /// </summary>
        public static string txtAmount {
            get {
                return ResourceManager.GetString("txtAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求金額.
        /// </summary>
        public static string txtBillingAmount {
            get {
                return ResourceManager.GetString("txtBillingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［請求予定］.
        /// </summary>
        public static string txtBillingPlan {
            get {
                return ResourceManager.GetString("txtBillingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日締.
        /// </summary>
        public static string txtClosingDay {
            get {
                return ResourceManager.GetString("txtClosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【社内共有情報】.
        /// </summary>
        public static string txtCompanyInternalCommonInfor {
            get {
                return ResourceManager.GetString("txtCompanyInternalCommonInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消費税率.
        /// </summary>
        public static string txtConsumptionTaxRate {
            get {
                return ResourceManager.GetString("txtConsumptionTaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【契約期間】.
        /// </summary>
        public static string txtContractPeriod {
            get {
                return ResourceManager.GetString("txtContractPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string txtDay {
            get {
                return ResourceManager.GetString("txtDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 決定.
        /// </summary>
        public static string txtDecision {
            get {
                return ResourceManager.GetString("txtDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［控除金額］.
        /// </summary>
        public static string txtDeductedAmount {
            get {
                return ResourceManager.GetString("txtDeductedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［納品日］.
        /// </summary>
        public static string txtDeliveryDate {
            get {
                return ResourceManager.GetString("txtDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入金日.
        /// </summary>
        public static string txtDepositPlanDate {
            get {
                return ResourceManager.GetString("txtDepositPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【詳細】.
        /// </summary>
        public static string txtDetail {
            get {
                return ResourceManager.GetString("txtDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【詳細名】.
        /// </summary>
        public static string txtDetailedName {
            get {
                return ResourceManager.GetString("txtDetailedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分割払い.
        /// </summary>
        public static string txtDevidedPayment {
            get {
                return ResourceManager.GetString("txtDevidedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［支払予定］.
        /// </summary>
        public static string txtDevidedPaymentPlan {
            get {
                return ResourceManager.GetString("txtDevidedPaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間幅.
        /// </summary>
        public static string txtDuration {
            get {
                return ResourceManager.GetString("txtDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 末.
        /// </summary>
        public static string txtEnd {
            get {
                return ResourceManager.GetString("txtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to にて終了.
        /// </summary>
        public static string txtEndAt {
            get {
                return ResourceManager.GetString("txtEndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【終了日】.
        /// </summary>
        public static string txtEndDate {
            get {
                return ResourceManager.GetString("txtEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［超過金額］.
        /// </summary>
        public static string txtExcessAmount {
            get {
                return ResourceManager.GetString("txtExcessAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 延長.
        /// </summary>
        public static string txtExtend {
            get {
                return ResourceManager.GetString("txtExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 途中終了.
        /// </summary>
        public static string txtFinishedInMiddle {
            get {
                return ResourceManager.GetString("txtFinishedInMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全終了.
        /// </summary>
        public static string txtFinishedNormal {
            get {
                return ResourceManager.GetString("txtFinishedNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 途中終了＋特殊精算.
        /// </summary>
        public static string txtFinishMiddleWithSpecialPayment {
            get {
                return ResourceManager.GetString("txtFinishMiddleWithSpecialPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy年MM月dd日.
        /// </summary>
        public static string txtFullDateFormat {
            get {
                return ResourceManager.GetString("txtFullDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【要見積書】.
        /// </summary>
        public static string txtHasEstimate {
            get {
                return ResourceManager.GetString("txtHasEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【要納品書】.
        /// </summary>
        public static string txtHasInvoice {
            get {
                return ResourceManager.GetString("txtHasInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string txtHour {
            get {
                return ResourceManager.GetString("txtHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※.
        /// </summary>
        public static string txtJapaneseAsterick {
            get {
                return ResourceManager.GetString("txtJapaneseAsterick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分.
        /// </summary>
        public static string txtMinute {
            get {
                return ResourceManager.GetString("txtMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月.
        /// </summary>
        public static string txtMonth {
            get {
                return ResourceManager.GetString("txtMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月精算分.
        /// </summary>
        public static string txtMonthlyPayment {
            get {
                return ResourceManager.GetString("txtMonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  様.
        /// </summary>
        public static string txtMr {
            get {
                return ResourceManager.GetString("txtMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【氏名】.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        public static string txtNone {
            get {
                return ResourceManager.GetString("txtNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備考.
        /// </summary>
        public static string txtNote {
            get {
                return ResourceManager.GetString("txtNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［請求回数］.
        /// </summary>
        public static string txtNumberOfBillings {
            get {
                return ResourceManager.GetString("txtNumberOfBillings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［支払回数］.
        /// </summary>
        public static string txtNumberOfPayments {
            get {
                return ResourceManager.GetString("txtNumberOfPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【受注先】.
        /// </summary>
        public static string txtOADestination {
            get {
                return ResourceManager.GetString("txtOADestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［受注先共有情報］.
        /// </summary>
        public static string txtOADestinationCommonInfor {
            get {
                return ResourceManager.GetString("txtOADestinationCommonInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【受注先責任者】.
        /// </summary>
        public static string txtOADestinationPICSekininsha {
            get {
                return ResourceManager.GetString("txtOADestinationPICSekininsha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【受注先担当】.
        /// </summary>
        public static string txtOADestinationPICTanto {
            get {
                return ResourceManager.GetString("txtOADestinationPICTanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回.
        /// </summary>
        public static string txtOccurrence {
            get {
                return ResourceManager.GetString("txtOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【発注先】.
        /// </summary>
        public static string txtOPDestination {
            get {
                return ResourceManager.GetString("txtOPDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［発注先共有情報］.
        /// </summary>
        public static string txtOPDestinationCommonInfor {
            get {
                return ResourceManager.GetString("txtOPDestinationCommonInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【発注先責任者】.
        /// </summary>
        public static string txtOPDestinationPICSekininsha {
            get {
                return ResourceManager.GetString("txtOPDestinationPICSekininsha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【発注先担当】.
        /// </summary>
        public static string txtOPDestinationPICTanto {
            get {
                return ResourceManager.GetString("txtOPDestinationPICTanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一括払い.
        /// </summary>
        public static string txtPackagePayment {
            get {
                return ResourceManager.GetString("txtPackagePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払金額.
        /// </summary>
        public static string txtPaymentAmount {
            get {
                return ResourceManager.GetString("txtPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払日.
        /// </summary>
        public static string txtPaymentDate {
            get {
                return ResourceManager.GetString("txtPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日払.
        /// </summary>
        public static string txtPaymentDay {
            get {
                return ResourceManager.GetString("txtPaymentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精算方法.
        /// </summary>
        public static string txtPaymentMethod {
            get {
                return ResourceManager.GetString("txtPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string txtPercentage {
            get {
                return ResourceManager.GetString("txtPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間.
        /// </summary>
        public static string txtPeriod {
            get {
                return ResourceManager.GetString("txtPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【再送】.
        /// </summary>
        public static string txtResend {
            get {
                return ResourceManager.GetString("txtResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------.
        /// </summary>
        public static string txtSeparatingLine {
            get {
                return ResourceManager.GetString("txtSeparatingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy年M月d日.
        /// </summary>
        public static string txtShortDateFormat {
            get {
                return ResourceManager.GetString("txtShortDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［サイト］.
        /// </summary>
        public static string txtSite {
            get {
                return ResourceManager.GetString("txtSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【件名】.
        /// </summary>
        public static string txtSubject {
            get {
                return ResourceManager.GetString("txtSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［時間単位］.
        /// </summary>
        public static string txtTimeUnit {
            get {
                return ResourceManager.GetString("txtTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単価.
        /// </summary>
        public static string txtUnitPrice {
            get {
                return ResourceManager.GetString("txtUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【作業場所】.
        /// </summary>
        public static string txtWorkPlace {
            get {
                return ResourceManager.GetString("txtWorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        public static string txtYear {
            get {
                return ResourceManager.GetString("txtYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 円.
        /// </summary>
        public static string txtYen {
            get {
                return ResourceManager.GetString("txtYen", resourceCulture);
            }
        }
    }
}
